### ISSUE TITLE
Set mapping context issue in starting application

### ISSUE THREAD

**Issue by bcfelix** [spring-projects/spring-data-neo4j#147]
I got the following error in starting the application.

java.lang.NoSuchMethodError: org.springframework.data.neo4j.repository.GraphRepositoryFactoryBean.setMappingContext(Lorg/springframework/data/mapping/context/MappingContext;)V
	at org.springframework.data.neo4j.repository.GraphRepositoryFactoryBean.afterPropertiesSet(GraphRepositoryFactoryBean.java:67)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1514)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1452)

It seems because of the setMappingContext method in org.springframework.data.neo4j.repository.GraphRepositoryFactoryBean is a protected method.

Note: I am using Spring data neo4j 2.3.2 and Spring data commons 1.6.1.

**Comment by mangrish** [comment]
Closed. Issue out of date.
