### ISSUE TITLE
Neo4j standalone problem in SDN 3.0

### ISSUE THREAD

**Issue by monitorjbl** [spring-projects/spring-data-neo4j#162]
After upgrading our application code to SDN 3.0.0.RELEASE from 3.0.0.RC1, our Neo4j instance will start throwing errors after some time. The remote Neo4j server will start throwing 500 errors on reads and writes, and the  stacktrace below will appear in the Neo4j logs. We're not actually using any transactions in our code, so I'm not sure what's going on here. This didn't appear to be a problem in 3.0.0.RC1, but it's possible that it just takes time to occur and we never left the server running long enough to experience it.

I'm guessing it's not a timing issue, but rather a certain number of reads or writes that will start to cause this issue. The only resolution that I've found is to restart the Neo4j server when this starts happening. I'm using the Neo4j 2.0.0 standalone on OSX right now, if that's any help.

Application stacktrace:

```
java.lang.RuntimeException: 500
	at org.neo4j.rest.graphdb.ExecutingRestAPI.createRestNode(ExecutingRestAPI.java:120)
	at org.neo4j.rest.graphdb.ExecutingRestAPI.createNode(ExecutingRestAPI.java:113)
	at org.neo4j.rest.graphdb.RestAPIFacade.createNode(RestAPIFacade.java:69)
	at org.springframework.data.neo4j.rest.SpringRestGraphDatabase.createNode(SpringRestGraphDatabase.java:69)
	at org.springframework.data.neo4j.support.mapping.EntityStateHandler.createNode(EntityStateHandler.java:145)
	at org.springframework.data.neo4j.support.mapping.EntityStateHandler.useOrCreateState(EntityStateHandler.java:136)
	at org.springframework.data.neo4j.support.mapping.Neo4jEntityConverterImpl.write(Neo4jEntityConverterImpl.java:163)
	at org.springframework.data.neo4j.support.mapping.Neo4jEntityPersister$CachedConverter.write(Neo4jEntityPersister.java:179)
	at org.springframework.data.neo4j.support.mapping.Neo4jEntityPersister.persist(Neo4jEntityPersister.java:243)
	at org.springframework.data.neo4j.support.mapping.Neo4jEntityPersister.persist(Neo4jEntityPersister.java:231)
	at org.springframework.data.neo4j.support.Neo4jTemplate.save(Neo4jTemplate.java:356)
	at org.springframework.data.neo4j.support.Neo4jTemplate.save(Neo4jTemplate.java:350)
```

Neo4j stacktrace: 

```
Mar 14, 2014 4:12:29 PM com.sun.jersey.server.impl.application.WebApplicationImpl _handleRequest
SEVERE: The RuntimeException could not be mapped to a response, re-throwing to the HTTP container
org.neo4j.graphdb.TransactionFailureException: Unable to get transaction.
    at org.neo4j.kernel.InternalAbstractGraphDatabase.transactionRunning(InternalAbstractGraphDatabase.java:989)
    at org.neo4j.kernel.InternalAbstractGraphDatabase.beginTx(InternalAbstractGraphDatabase.java:962)
    at org.neo4j.kernel.TransactionBuilderImpl.begin(TransactionBuilderImpl.java:43)
    at org.neo4j.kernel.InternalAbstractGraphDatabase.beginTx(InternalAbstractGraphDatabase.java:949)
    at org.neo4j.server.rest.transactional.TransactionalRequestDispatcher.dispatch(TransactionalRequestDispatcher.java:52)
    at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:288)
    at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
    at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
    at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
    at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
    at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1469)
    at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1400)
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1349)
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1339)
    at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:537)
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:699)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:698)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1506)
    at org.neo4j.server.rest.security.SecurityFilter.doFilter(SecurityFilter.java:112)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1477)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:503)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:211)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1096)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:432)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1030)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
    at org.eclipse.jetty.server.Server.handle(Server.java:445)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:268)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:229)
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
    at java.lang.Thread.run(Thread.java:722)
Caused by: javax.transaction.SystemException: TM has encountered some problem, please perform necessary action (tx recovery/restart)
    at org.neo4j.kernel.impl.transaction.TxManager.assertTmOk(TxManager.java:344)
    at org.neo4j.kernel.impl.transaction.TxManager.getTransaction(TxManager.java:709)
    at org.neo4j.kernel.InternalAbstractGraphDatabase.transactionRunning(InternalAbstractGraphDatabase.java:985)
    ... 37 more 
Caused by: java.nio.channels.ClosedChannelException
    at sun.nio.ch.FileChannelImpl.ensureOpen(FileChannelImpl.java:94)
    at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:691)
    at org.neo4j.kernel.impl.transaction.xaframework.DirectMappedLogBuffer.writeOut(DirectMappedLogBuffer.java:159)
    at org.neo4j.kernel.impl.transaction.xaframework.DirectMappedLogBuffer.force(DirectMappedLogBuffer.java:172)
    at org.neo4j.kernel.impl.transaction.TxLog.force(TxLog.java:167)
    at org.neo4j.kernel.impl.transaction.TxLog.switchToLogFile(TxLog.java:591)
    at org.neo4j.kernel.impl.transaction.TxManager.getTxLog(TxManager.java:253)
    at org.neo4j.kernel.impl.transaction.TxManager.writeStartRecord(TxManager.java:360)
    at org.neo4j.kernel.impl.transaction.TransactionImpl.enlistResource(TransactionImpl.java:154)
    at org.neo4j.kernel.impl.persistence.PersistenceManager.getResource(PersistenceManager.java:223)
    at org.neo4j.kernel.impl.persistence.PersistenceManager.currentKernelTransaction(PersistenceManager.java:84)
    at org.neo4j.kernel.impl.core.ThreadToStatementContextBridge.transaction(ThreadToStatementContextBridge.java:53)
    at org.neo4j.kernel.impl.core.ThreadToStatementContextBridge.instance(ThreadToStatementContextBridge.java:47)
    at org.neo4j.kernel.impl.core.NodeProxy.getPropertyKeys(NodeProxy.java:290)
    at org.neo4j.server.helpers.PropertyTypeDispatcher.consumeProperties(PropertyTypeDispatcher.java:51)
    at org.neo4j.server.rest.repr.PropertiesRepresentation.serialize(PropertiesRepresentation.java:50)
    at org.neo4j.server.rest.repr.NodeRepresentation.extraData(NodeRepresentation.java:142)
    at org.neo4j.server.rest.repr.ObjectRepresentation.serialize(ObjectRepresentation.java:147)
    at org.neo4j.server.rest.repr.MappingRepresentation.serialize(MappingRepresentation.java:41)
    at org.neo4j.server.rest.repr.OutputFormat$1.write(OutputFormat.java:160)
    at com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:71)
    at com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:57)
    at com.sun.jersey.spi.container.ContainerResponse.write(ContainerResponse.java:306)
    at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1437)
    ... 26 more

**Comment by mangrish** [comment]
Closed. Issue out of date.
