### ISSUE TITLE
Build fails with IOException: Too many open files on some environments [DATAGRAPH-1242]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-data-neo4j#1803]
**[Mark Paluch](https://jira.spring.io/secure/ViewProfile.jspa?name=mp911de)** opened **[DATAGRAPH-1242](https://jira.spring.io/browse/DATAGRAPH-1242?redirect=false)** and commented

Running the Maven fails on some environments that limit number of open files.

Raising limits via `ulimit -n 48000` does not seem to affect the build.

Failure:

```
Caused by: io.netty.channel.ChannelException: failed to open a new selector
	at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:168)
	at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:142)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:127)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:36)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
	... 78 common frames omitted
Caused by: java.io.IOException: Too many open files
	at sun.nio.ch.IOUtil.makePipe(Native Method)
	at sun.nio.ch.KQueueSelectorImpl.<init>(KQueueSelectorImpl.java:84)
	at sun.nio.ch.KQueueSelectorProvider.openSelector(KQueueSelectorProvider.java:42)
	at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:166)
	... 82 common frames omitted
```

Steps to reproduce:

`mvn clean install`

---
No further details from [DATAGRAPH-1242](https://jira.spring.io/browse/DATAGRAPH-1242?redirect=false)

**Comment by michael-simons** [comment]
Thanks @mp911de. I think that was closed in DATAGRAPH-1322 and I just didn't spot this ticket.

SDN 5.3 can be build with

```
ulimit -n 8192 
./mvnw clean verify
```

at least on macOS inside bash. Below that things get messy due to the use of the embedded database.
