### ISSUE TITLE
Annotations on RelationshipEntity methods not working

### ISSUE THREAD

**Issue by freebim** [spring-projects/spring-data-neo4j#201]
Setting Annotation (like ``` @Id, @StartNode, @EndNode, @RelationshipType```) to fields of RelationshipEntity works, setting them to getter methods of RelationshipEntity doesn't work.

Working example:
```java
@RelationshipEntity
public class BaseRel {

	@GraphId
	@Id
	private Long id;
	
	@StartNode 
	private BaseNode n1;

	@EndNode 
	private BaseNode n2;
	
	@RelationshipType
	private RelationTypeEnum type;
```

Not working example:
```java
@RelationshipEntity
public class BaseRel {

	private Long id;
	private BaseNode n1;
	private BaseNode n2;
	private RelationTypeEnum type;

	@GraphId
	@Id
	public Long getId() {
		return this.id;
	}
	
	@StartNode 
	public BaseNode getN1()
		return this.n1;
	}

	@EndNode 
	public BaseNode getN2() {
		return this.n2;
	}
	
	@RelationshipType
	public RelationTypeEnum getType() {
		return this.type;
	}
...
```

The Exception thrown when building the application:
```
org.springframework.data.mapping.model.MappingException: No id property in class ...
	at org.springframework.data.neo4j.support.mapping.Neo4jPersistentEntityImpl.verify(Neo4jPersistentEntityImpl.java:93)
	at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:298)
	at org.springframework.data.neo4j.support.mapping.Neo4jMappingContext.addPersistentEntity(Neo4jMappingContext.java:69)
	at org.springframework.data.neo4j.support.mapping.Neo4jMappingContext.addPersistentEntity(Neo4jMappingContext.java:49)
	at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:257)
	at org.springframework.data.mapping.context.AbstractMappingContext.initialize(AbstractMappingContext.java:373)
	at org.springframework.data.neo4j.support.mapping.Neo4jMappingContext.initialize(Neo4jMappingContext.java:111)
	at org.springframework.data.mapping.context.AbstractMappingContext.afterPropertiesSet(AbstractMappingContext.java:363)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1612)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1549)
	... 96 more
```

**Comment by mangrish** [comment]
Closed. Issue out of date.
