### ISSUE TITLE
Spring-Data-Neo4j is not able to load immediate connections [DATAGRAPH-1450]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-neo4j#2012]
**[Sid Med](https://jira.spring.io/secure/ViewProfile.jspa?name=JIRAUSER50732)** opened **[DATAGRAPH-1450](https://jira.spring.io/browse/DATAGRAPH-1450?redirect=false)** and commented

Take any spring data neo4j, and try to load one node along with its immediate connections. 

Take the sample project about movies for example, and try to load a Movie object along with all its actors, directors, producers, etc...  You won't be able to do that. In order to accomplish that, you would need to first load a movie object by itself, and then initiate separate calls to the database to load the other nodes separately and add them to the movie object yourself. For example, assume the Movie entity node has the following connections:

```java
@Node
public class Movie {
     @Id
     private final Long id;


     private String title;


     @Property("tagline")
     private final String description;

     @Relationship(type = "ACTED_IN", direction = Direction.INCOMING)
     private List<Actor> actors = new ArrayList<>();

     @Relationship(type = "DIRECTED", direction = Direction.INCOMING)
     private List<Person> directors = new ArrayList<>();

    @Relationship(type = "PRODUCED", direction = Direction.INCOMING)
    private List<Person> producers = new ArrayList<>();

    @Relationship(type = "WROTE", direction = Direction.INCOMING)
    private List<Person> writers = new ArrayList<>();

    @Relationship(type = "REVIEWED", direction = Direction.INCOMING)
    private List<Person> reviewers = new ArrayList<>();

    // getter method, etc... 

}
```

and have a method in the MovieRepository like this:

```java
    @Query("MATCH (m:Movie)<-[a:ACTED_IN]-(p:Person) where id(m) = $0 return m,    collect(a) as actors")
    Movie movieById(Long id);
```

have some controller rest api that hits the above method:

```java
@GetMapping("/movie/\{id}")
public Movie getMovieById(@PathVariable Long id) {
    return movieRepository.movieById(id);
}
```

when you hit the rest api to load a given movie by its ID (say curl http://localhost:8080/movie/9), the movie you get only contain the attributes of the Movie Entity itself, no producers, no directors, no actors are returned (all empty). It does not matter how you do the query in the movie repository. All the following queries won't succeed in returning any of the immediate connection nodes of the Movie object:

```java
@Query("MATCH (m:Movie)<-[a]-(p:Person) where id(m) = $id return *")

@Query("MATCH (m:Movie)<-[a:ACTED_IN]-(p:Person) where id(m) = $0 return *")

@Query("MATCH (m:Movie)<-[a:PRODUCED]-(p:Person) where id(m) = $0 return *")

@Query("MATCH (m:Movie)<-[a:PRODUCED]-(p:Person) where id(m) = $0 return m, collect(a) as producers")
```

  

---

**Affects:** 6.0.1 (2020.0.1)

**Comment by hamidbm** [comment]
Thank you Gerit and Michael for helping out. It turned out that I was using the id attribute (as a Long) for primary key for the Movie object while in the neo4j movie sample data, the movies nodes don't have an attribute called id (the nodes have an ID that you can access in cypher with id(node), but there was no "id" attribute on the nodes despite the fact that the graph UI displays the value of id when you select a node. So I have to add the "id" attribute to all the nodes with this cypher:

MATCH (n) SET n.id = id(n);

After doing that, I was able to get projection data when using "id" as the primary key. 

I have create a new sample project on GitHub: https://github.com/hamidbm/movies-modular/tree/master
I have invited you and Michel to collaborate. The project is not yet perfect and once it is ready, I will make it public for everybody to benefit from. 
 
There is a bug in this project that needs to be solved. Projection is not working. Anything else is working fine. The project is structured into a modula form (jigsaw modules) where the repository classes along with the service implementation is a separate module, the interfaces for the data and service are in a separate module (movies.api) and the rest controller in a separate module (movies.web). 

When the project is not modular, the bug is not there (projections work fine). This bug appears only when the project is divided into modules. 

The bug happens in the following line of DefaultNeo4jClient class (line 284):
    Result result = runnableStatement.runWith(statementRunner);

the result is empty and does not contain the node being fetched. The error displayed on the console is this:

500 Server Error for HTTP GET "/person/6"

org.springframework.dao.InvalidDataAccessResourceUsageException: Expected parameter(s): id; Error code 'Neo.ClientError.Statement.ParameterMissing'
	at org.springframework.data.neo4j.repository.support.Neo4jPersistenceExceptionTranslator.translateImpl(Neo4jPersistenceExceptionTranslator.java:105) ~[spring-data-neo4j-6.0.0.jar:?]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ HTTP GET "/person/6" [ExceptionHandlingWebHandler]
Stack trace:
		at org.springframework.data.neo4j.repository.support.Neo4jPersistenceExceptionTranslator.translateImpl(Neo4jPersistenceExceptionTranslator.java:105) ~[spring-data-neo4j-6.0.0.jar:?]
		at org.springframework.data.neo4j.repository.support.Neo4jPersistenceExceptionTranslator.translateExceptionIfPossible(Neo4jPersistenceExceptionTranslator.java:91) ~[spring-data-neo4j-6.0.0.jar:?]
		at org.springframework.data.neo4j.core.DefaultNeo4jClient.potentiallyConvertRuntimeException(DefaultNeo4jClient.java:176) ~[spring-data-neo4j-6.0.0.jar:?]
		at org.springframework.data.neo4j.core.DefaultNeo4jClient.access$400(DefaultNeo4jClient.java:57) ~[spring-data-neo4j-6.0.0.jar:?]
		at org.springframework.data.neo4j.core.DefaultNeo4jClient$DefaultRecordFetchSpec.one(DefaultNeo4jClient.java:291) ~[spring-data-neo4j-6.0.0.jar:?]
		at org.springframework.data.neo4j.core.Neo4jTemplate$DefaultExecutableQuery.getSingleResult(Neo4jTemplate.java:533) ~[spring-data-neo4j-6.0.0.jar:?]
		at org.springframework.data.neo4j.repository.query.Neo4jQueryExecution$DefaultQueryExecution.execute(Neo4jQueryExecution.java:53) ~[spring-data-neo4j-6.0.0.jar:?]
		at org.springframework.data.neo4j.repository.query.AbstractNeo4jQuery.execute(AbstractNeo4jQuery.java:76) ~[spring-data-neo4j-6.0.0.jar:?]
		at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:137) ~[spring-data-commons-2.4.1.jar:?]
		at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:121) ~[spring-data-commons-2.4.1.jar:?]
		at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:152) ~[spring-data-commons-2.4.1.jar:?]
		at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:131) ~[spring-data-commons-2.4.1.jar:?]
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.1.jar:?]
		at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:80) ~[spring-data-commons-2.4.1.jar:?]
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.1.jar:?]
		at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:371) ~[spring-tx-5.3.1.jar:?]
		at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:134) ~[spring-tx-5.3.1.jar:?]
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.1.jar:?]
		at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137) ~[spring-tx-5.3.1.jar:?]
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.1.jar:?]
		at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) ~[spring-aop-5.3.1.jar:?]
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.1.jar:?]
		at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215) ~[spring-aop-5.3.1.jar:?]
		at com.sun.proxy.$Proxy104.getDetailsById(Unknown Source) ~[?:?]
		at com.example.movies.service.impl.PersonServiceImpl.personDetailsById(PersonServiceImpl.java:20) ~[main/:?]
		at com.example.movies.web.PersonController.personById(PersonController.java:24) ~[main/:?]
		at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
		at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[?:?]
		at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
		at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
		at org.springframework.web.reactive.result.method.InvocableHandlerMethod.lambda$invoke$0(InvocableHandlerMethod.java:146) ~[spring-webflux-5.3.1.jar:?]
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:125) [reactor-core-3.4.0.jar:?]
		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1784) [reactor-core-3.4.0.jar:?]
		at reactor.core.publisher.MonoZip$ZipCoordinator.signal(MonoZip.java:251) [reactor-core-3.4.0.jar:?]
		at reactor.core.publisher.MonoZip$ZipInner.onNext(MonoZip.java:336) [reactor-core-3.4.0.jar:?]
		at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180) [reactor-core-3.4.0.jar:?]
		at reactor.core.publisher.FluxDefaultIfEmpty$DefaultIfEmptySubscriber.onNext(FluxDefaultIfEmpty.java:99) [reactor-core-3.4.0.jar:?]
		at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:73) [reactor-core-3.4.0.jar:?]
		at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2346) [reactor-core-3.4.0.jar:?]
		at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2154) [reactor-core-3.4.0.jar:?]
		at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:2028) [reactor-core-3.4.0.jar:?]
		at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:191) [reactor-core-3.4.0.jar:?]
		at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53) [reactor-core-3.4.0.jar:?]
		at reactor.core.publisher.Mono.subscribe(Mono.java:3972) [reactor-core-3.4.0.jar:?]
		at reactor.core.publisher.MonoZip.subscribe(MonoZip.java:128) [reactor-core-3.4.0.jar:?]
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) [reactor-core-3.4.0.jar:?]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) [reactor-core-3.4.0.jar:?]
		at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:154) [reactor-core-3.4.0.jar:?]
		at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:56) [reactor-core-3.4.0.jar:?]
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) [reactor-core-3.4.0.jar:?]
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157) [reactor-core-3.4.0.jar:?]
		at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:73) [reactor-core-3.4.0.jar:?]
		at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82) [reactor-core-3.4.0.jar:?]
		at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.innerNext(FluxConcatMap.java:281) [reactor-core-3.4.0.jar:?]
		at reactor.core.publisher.FluxConcatMap$ConcatMapInner.onNext(FluxConcatMap.java:860) [reactor-core-3.4.0.jar:?]
		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:127) [reactor-core-3.4.0.jar:?]
		at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180) [reactor-core-3.4.0.jar:?]
		at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2346) [reactor-core-3.4.0.jar:?]
		at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.request(MonoPeekTerminal.java:139) [reactor-core-3.4.0.jar:?]
		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:169) [reactor-core-3.4.0.jar:?]
		at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2154) [reactor-core-3.4.0.jar:?]
		at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:2028) [reactor-core-3.4.0.jar:?]
		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:96) [reactor-core-3.4.0.jar:?]
		at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onSubscribe(MonoPeekTerminal.java:152) [reactor-core-3.4.0.jar:?]
		at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54) [reactor-core-3.4.0.jar:?]
		at reactor.core.publisher.Mono.subscribe(Mono.java:3987) [reactor-core-3.4.0.jar:?]
		at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:448) [reactor-core-3.4.0.jar:?]
		at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onSubscribe(FluxConcatMap.java:218) [reactor-core-3.4.0.jar:?]
		at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:164) [reactor-core-3.4.0.jar:?]
		at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:86) [reactor-core-3.4.0.jar:?]
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) [reactor-core-3.4.0.jar:?]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) [reactor-core-3.4.0.jar:?]
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) [reactor-core-3.4.0.jar:?]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) [reactor-core-3.4.0.jar:?]
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) [reactor-core-3.4.0.jar:?]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) [reactor-core-3.4.0.jar:?]
		at reactor.core.publisher.Mono.subscribe(Mono.java:3987) [reactor-core-3.4.0.jar:?]
		at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:173) [reactor-core-3.4.0.jar:?]
		at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:56) [reactor-core-3.4.0.jar:?]
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) [reactor-core-3.4.0.jar:?]
		at reactor.netty.http.server.HttpServer$HttpServerHandle.onStateChange(HttpServer.java:611) [reactor-netty-http-1.0.1.jar:?]
		at reactor.netty.ReactorNetty$CompositeConnectionObserver.onStateChange(ReactorNetty.java:612) [reactor-netty-core-1.0.1.jar:?]
		at reactor.netty.transport.ServerTransport$ChildObserver.onStateChange(ServerTransport.java:453) [reactor-netty-core-1.0.1.jar:?]
		at reactor.netty.http.server.HttpServerOperations.onInboundNext(HttpServerOperations.java:510) [reactor-netty-http-1.0.1.jar:?]
		at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:94) [reactor-netty-core-1.0.1.jar:?]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.54.Final.jar:?]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.54.Final.jar:?]
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.54.Final.jar:?]
		at reactor.netty.http.server.HttpTrafficHandler.channelRead(HttpTrafficHandler.java:185) [reactor-netty-http-1.0.1.jar:?]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.54.Final.jar:?]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.54.Final.jar:?]
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.54.Final.jar:?]
		at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) [netty-transport-4.1.54.Final.jar:?]
		at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-codec-4.1.54.Final.jar:?]
		at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [netty-codec-4.1.54.Final.jar:?]
		at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) [netty-transport-4.1.54.Final.jar:?]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.54.Final.jar:?]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.54.Final.jar:?]
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.54.Final.jar:?]
		at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.54.Final.jar:?]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.54.Final.jar:?]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.54.Final.jar:?]
		at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.54.Final.jar:?]
		at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-transport-4.1.54.Final.jar:?]
		at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-transport-4.1.54.Final.jar:?]
		at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [netty-transport-4.1.54.Final.jar:?]
		at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [netty-transport-4.1.54.Final.jar:?]
		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.54.Final.jar:?]
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.54.Final.jar:?]
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.54.Final.jar:?]
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.54.Final.jar:?]
		at java.lang.Thread.run(Thread.java:832) [?:?]

**Comment by michael-simons** [comment]
Thanks for your input and feedback.

Yes, wrt to `@Id`, this is the correct and expected behavior. Please read this:
https://docs.spring.io/spring-data/neo4j/docs/6.0.2/reference/html/#mapping.annotations.id

Especially this:

> On an attribute of type long or Long, @Id can be used with @GeneratedValue. This maps the Neo4j internal id, which is not a property on a node or relationship and usually not visible, to the attribute and allows SDN to retrieve individual instances of the class.
