### ISSUE TITLE
Spring Data Neo4J 6.0.1 throws Exception when connecting to Neo4j 3.5 [DATAGRAPH-1451]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-data-neo4j#2013]
**[Marcos Stival](https://jira.spring.io/secure/ViewProfile.jspa?name=JIRAUSER50721)** opened **[DATAGRAPH-1451](https://jira.spring.io/browse/DATAGRAPH-1451?redirect=false)** and commented

Hi, I'm using **SDN 6.0.1** and running a **Neo4J v3.5**. I'm +not using any of the Reactive features+ but when I try to connect to a Neo4J instance v3.5.x I get this Exception.

 

Is there any way to configure this behavior? Thanks 

```java
// code placeholder
org.neo4j.driver.exceptions.ClientException: Driver is connected to the database that does not support driver reactive API. In order to use the driver reactive API, please upgrade to neo4j 4.0.0 or later.org.neo4j.driver.exceptions.ClientException: Driver is connected to the database that does not support driver reactive API. In order to use the driver reactive API, please upgrade to neo4j 4.0.0 or later. at org.neo4j.driver.internal.cursor.AsyncResultCursorOnlyFactory.rxResult(AsyncResultCursorOnlyFactory.java:80) ~[neo4j-java-driver-4.1.1.jar:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c] at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146) ~[na:na] at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[na:na] at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2137) ~[na:na] at org.neo4j.driver.internal.util.Futures.lambda$asCompletionStage$0(Futures.java:93) ~[neo4j-java-driver-4.1.1.jar:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c] at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577) ~[neo4j-java-driver-4.1.1.jar:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c] at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551) ~[neo4j-java-driver-4.1.1.jar:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c] at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.DefaultPromise.access$200(DefaultPromise.java:35) ~[neo4j-java-driver-4.1.1.jar:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c] at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:501) ~[neo4j-java-driver-4.1.1.jar:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c] at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[neo4j-java-driver-4.1.1.jar:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c] at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[neo4j-java-driver-4.1.1.jar:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c] at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[neo4j-java-driver-4.1.1.jar:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c] at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[neo4j-java-driver-4.1.1.jar:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c] at org.neo4j.driver.internal.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[neo4j-java-driver-4.1.1.jar:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c] at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[neo4j-java-driver-4.1.1.jar:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c] at java.base/java.lang.Thread.run(Thread.java:832) ~[na:na]
```

---

**Affects:** 6.0.1 (2020.0.1)

**Comment by michael-simons** [comment]
Hi @mrksph I hope this you're correct handle on GH.

I have verified this another time and you can do this yourself if you like. You need Docker and JDK 11 todo so:

```
docker run --publish=7474:7474 --publish=7687:7687 -e 'NEO4J_AUTH=neo4j/secret'  neo4j:3.5
SDN_NEO4J_URL=bolt://localhost:7687 SDN_NEO4J_PASSWORD=secret ./mvnw  clean verify
```

We have however identified one reactive infrastructure *test* that was missing the required indicator that it will use reactive features. This is gonna be fixed in a following commit.

Thanks for your contributions!

**Comment by mrksph** [comment]
Hi @michael-simons , thanks for comming back at this issue. As I'm typing this, I'm running into the same problem again. 
I'm using Spring Boot 2.4.0, Neo4J v3.5.17 locally.
I have my real project and a dummy project to test for edge cases. My dummy project compiles and connects successfully to my local Neo4j instance while my real project seems to identify a Reactive dependency where there aren't any and won't let me run the app.

I have search through the whole project and there aren't any reference to the Reactive API... 

What kind of information can I supply to help you?

**Comment by michael-simons** [comment]
If you use

* `ReactiveNeo4jClient`
* `ReactiveNeo4jTemplate`
* Or have repository that `extends ReactiveNeo4jRepository<Domain, ID>`

then a database 4.0+ is required.

Dependencies would be a thing to start along with `application.properties` or `application.yml`.
