### ISSUE TITLE
SDN 6.0.x detects transitive dependencies' usage of Reactor library as own and fails to connect to older versions of Neo4J

### ISSUE THREAD

**Issue by mrksph** [spring-projects/spring-data-neo4j#2116]
Hi,

EDIT: I created a related issue under Spring Boot Actuator, https://github.com/spring-projects/spring-boot/issues/24838

I've been struggling with this problem for a while. 
I'm using Spring Boot v2.4.1 with SDN v6.0.1. 
The problem is when I try to connect to a Neo4j instance version 3.5.17 it fails with the following exception:
```
org.neo4j.driver.exceptions.ClientException: Driver is connected to the database that does not support driver reactive API. In order to use the driver reactive API, please upgrade to neo4j 4.0.0 or later.
	at org.neo4j.driver.internal.cursor.AsyncResultCursorOnlyFactory.rxResult(AsyncResultCursorOnlyFactory.java:80) ~[neo4j-java-driver-4.1.1.jar:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2137) ~[na:na]
	at org.neo4j.driver.internal.util.Futures.lambda$asCompletionStage$0(Futures.java:93) ~[neo4j-java-driver-4.1.1.jar:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
	at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577) ~[neo4j-java-driver-4.1.1.jar:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
	at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551) ~[neo4j-java-driver-4.1.1.jar:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
	at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.DefaultPromise.access$200(DefaultPromise.java:35) ~[neo4j-java-driver-4.1.1.jar:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
	at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:501) ~[neo4j-java-driver-4.1.1.jar:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
	at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[neo4j-java-driver-4.1.1.jar:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
	at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[neo4j-java-driver-4.1.1.jar:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[neo4j-java-driver-4.1.1.jar:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
	at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[neo4j-java-driver-4.1.1.jar:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
	at org.neo4j.driver.internal.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[neo4j-java-driver-4.1.1.jar:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
	at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[neo4j-java-driver-4.1.1.jar:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
	at java.base/java.lang.Thread.run(Thread.java:832) ~[na:na]
```

After debugging Spring's internals, I've found out where it checks for Reactive API usage. The check really only looks if Reactor's library is loaded in the ApplicationContext.

From Spring Boot Actuate Autoconfigure HealthEndpointConfiguration class:

```
@Bean
@ConditionalOnMissingBean
HealthContributorRegistry healthContributorRegistry(ApplicationContext applicationContext,
    	HealthEndpointGroups groups) {
    Map<String, HealthContributor> healthContributors = new LinkedHashMap<>(
    		applicationContext.getBeansOfType(HealthContributor.class));
    if (ClassUtils.isPresent("reactor.core.publisher.Flux", applicationContext.getClassLoader())) {
    	healthContributors.putAll(new AdaptedReactiveHealthContributors(applicationContext).get());
    }
    return new AutoConfiguredHealthContributorRegistry(healthContributors, groups.getNames());
}
``` 

I don't use Reactor library in my project though Reactor library is loaded as a transitive dependency because of Spring Integration Test (it's not scoped as a test dependency as it should but that's not the matter). 

Here we can see Reactor as a dependency from Spring Integration Test's dependency tree from the output of 'mvn dependency:tree':
```
[INFO] +- org.springframework.integration:spring-integration-test:jar:5.4.2:compile
[INFO] |  +- org.springframework.integration:spring-integration-core:jar:5.4.2:compile
[INFO] |  |  +- org.springframework:spring-messaging:jar:5.3.2:compile
[INFO] |  |  +- org.springframework.retry:spring-retry:jar:1.3.0:compile
[INFO] |  |  |  \- javax.annotation:javax.annotation-api:jar:1.3.2:compile
[INFO] |  |  \- io.projectreactor:reactor-core:jar:3.4.1:compile
```

It looks like random behavior. In my real project sometimes it connects without a problem, sometimes it doesn't. 
I also have a demo project where I'm trying to replicate this but when it reaches the breakpoint in HealthEndpointConfiguration the check for Reactor's usage sometimes returns false.

**Comment by mrksph** [comment]
Ok, after some researching I think this is more of a Spring Boot Actuator Autoconfigure problem. 

Here's the commit that adds that check. 
https://github.com/spring-projects/spring-boot/commit/ae5ae72889926d1eabe1ca492e0d77479d9c659e

So the problem is that if Spring Boot Actuator detects Reactor in the classpath (even as a transitive dependency) it instantiates a ReactiveHealthcheckEndpoint. When querying database as part of getHeatlh process it does it as a Reactive component, making Neo4j Driver throw a ClientException.

**Comment by snicoll** [comment]
I suggest closing this issue to avoid wasted efforts on two separate issue that are describing the same problem.

**Comment by mrksph** [comment]
> I suggest closing this issue to avoid wasted efforts on two separate issue that are describing the same problem.

Ok, yes I think its more of an Actuator issue. Thanks
