### ISSUE TITLE
Polymorphic query do no longer work in 6.0.6

### ISSUE THREAD

**Issue by aleksanderlech** [spring-projects/spring-data-neo4j#2199]
Hello,

I am trying to upgrade my spring-data-neo4j to the 6.0.6 and facing issues with polymorphic queries.

My model is something like:

```
@Node
public abstract class AbstractNode implements Serializable, Comparable<AbstractNode> {

    @Id @GeneratedValue
    @Getter @Setter
    private Long id;

    @Getter @Setter
    @Field(merge = true)
    private String name;

}

@Node(labels = "Cat")
public class CatNode extends AbstractNode {}

@Node(labels = "Dog")
public class DogNode extends AbstractNode {}

```
Now consider the following repository

```
@Repository
public interface PetsRepository extends Neo4jRepository<AbstractNode, Long> {

    @Query("MATCH (n {name: $name}) RETURN n")
    List<AbstractNode> findPets(String name);

}
```

That approach was perfectly working in the previous version giving me instances of Cat and Dog basing on the labels. Now I am getting:

```
org.springframework.data.neo4j.core.mapping.NoRootNodeMappingException: Could not find mappable nodes or relationships inside Record<{n: node<77>}> for org.springframework.data.neo4j.core.mapping.DefaultNeo4jPersistentEntity@3357ea6c
	at org.springframework.data.neo4j.core.mapping.DefaultNeo4jEntityConverter.read(DefaultNeo4jEntityConverter.java:102)
```

After debugging the DefaultNeo4jEntityConverter I noticed it gets the AbstractNode and expect that the the node will be labeled as AbstractNode. I know I could achieve polymophic queries by adding extra labels to all of my entities in database but I guess its not a good way to go. I don't see any reason why I could just not work out of the box in the way above having in mind that it was perfectly working in the previous version.

Is this something that might be supported in the future? Or should I change my model. If yes please advise whats the correct way of doing such polymorphic queries in this version of spring-data-neo4j.

**Comment by meistermeier** [comment]
Thanks for your input. Your assumption and analysis is 100% right.
Given an `AbstractNode` repository, the mapping logic only knows about this particular label for the determination of the node that we internally named root node.
Some general information about the mapping process: Because SDN works record oriented, it needs to figure out which of the nodes in the record matches the contract with the repository type best. Therefor it strictly checks for the parent class' label.
I am a little bit torn because the rule is: If you apply a `@Node` annotation on the parent (abstract) class this will automatically generate this additional label and apply it to the concrete nodes when querying with generated queries or persisting them. On the other hand without the `@Node` annotation the `AbstractNode` is not defining a real entity but is more a technical, for the graph invisible bit, that should not be used in the repository definition.
I will have a look if a more relaxed mapping approach could work without recognizing wrong nodes as the root nodes.

**Comment by meistermeier** [comment]
Solved with #2200

**Comment by aleksanderlech** [comment]
Thank you very much for your help.

**Comment by michael-simons** [comment]
Thank you for using our project AND providing feedback. That’s part of the story too. 👍

**Comment by aleksanderlech** [comment]
Hello @michael-simons , I was little away from the upgrade process so I had no really chance to test it by today.
I see that the current implementation still requires my nodes to have all of the Labels throughout the model - I don't really understand why it has to be like that and can't work as it did before.

I fully agree that in case of inheritance, where some other labels are defined with @Node on the way, we should match all of the labels but if an Abstract class is not annotate with anything it's just technical and has no label. 

So coming back to my pets example I would like the framework to initialize the final concrete class by matching the target label (Cat, Dog) without requiring me to add the AbstractEntity label to all of the database nodes.

Thank you very much for your support.

**Comment by aleksanderlech** [comment]
Hello @michael-simons , any opinion on this? It still block us from upgrading the Spring Boot version...

**Comment by meistermeier** [comment]
Do you refer to generated queries? So unrelated to this issue?
Yes, unfortunately this is needed at the moment because we need to hold information e.g. identifier etc. defined in an abstract class in a valid "Spring Data" entity definition to make use of the common functionality.
I can see a certain point in having abstract classes available as technical layers only but this would mean, beside other things that I need to think about, as a consequence that you would not be able to define a repository for this abstraction level.
If you could live with the potential consequences and want to have us a look, please file a new PR.

**Comment by aleksanderlech** [comment]
Hello, I don't refer to queries, I refer to the method how the neo4j records are mapped into Java objects.

However now I am a little confused as I look at your code in tests and according to that it should work exactly as I expect.

The method annotated with `@Query` looks as follows:

`Set<AbstractNodeEntity> findRelatedNodes(String number, int limit);`

Abstract node looks like that:

```
public abstract class AbstractNodeEntity implements NodeEntity {

    /**
     * Unique internal node id
     */
    @Id
    @GeneratedValue
    @Getter @Setter
    private Long id;

[...]
}
```

And sample node:

```
@org.springframework.data.neo4j.core.schema.Node(labels = "License")
public class LicenseNode extends AbstractNodeEntity {

    @Getter @Setter
    private String number;

[...]

```

And still after the query is executed I got:

```
org.springframework.data.mapping.MappingException: Error mapping Record<{p: node<17>}>
	at app//org.springframework.data.neo4j.core.mapping.DefaultNeo4jEntityConverter.read(DefaultNeo4jEntityConverter.java:114)
	at app//org.springframework.data.neo4j.core.mapping.DefaultNeo4jEntityConverter.read(DefaultNeo4jEntityConverter.java:69)
	at app//org.springframework.data.neo4j.core.mapping.Schema.lambda$getRequiredMappingFunctionFor$0(Schema.java:96)
	at app//org.springframework.data.neo4j.core.PreparedQuery$AggregatingMappingFunction.apply(PreparedQuery.java:239)
	at app//org.springframework.data.neo4j.core.PreparedQuery$AggregatingMappingFunction.apply(PreparedQuery.java:159)
	at app//org.springframework.data.neo4j.core.DelegatingMappingFunctionWithNullCheck.apply(DelegatingMappingFunctionWithNullCheck.java:45)
	at app//org.springframework.data.neo4j.core.DelegatingMappingFunctionWithNullCheck.apply(DelegatingMappingFunctionWithNullCheck.java:35)
	at app//org.springframework.data.neo4j.core.DefaultNeo4jClient$DefaultRecordFetchSpec.lambda$partialMappingFunction$0(DefaultNeo4jClient.java:501)
	at java.base@15.0.6/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base@15.0.6/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base@15.0.6/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base@15.0.6/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base@15.0.6/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base@15.0.6/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base@15.0.6/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base@15.0.6/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at app//org.springframework.data.neo4j.core.DefaultNeo4jClient$DefaultRecordFetchSpec.all(DefaultNeo4jClient.java:486)
	at java.base@15.0.6/java.util.Optional.map(Optional.java:258)
	at app//org.springframework.data.neo4j.core.Neo4jTemplate$DefaultExecutableQuery.getResults(Neo4jTemplate.java:975)
	at app//org.springframework.data.neo4j.repository.query.Neo4jQueryExecution$DefaultQueryExecution.execute(Neo4jQueryExecution.java:51)
	at app//org.springframework.data.neo4j.repository.query.AbstractNeo4jQuery.execute(AbstractNeo4jQuery.java:94)
	at app//org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:137)
	at app//org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:121)
	at app//org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:159)
	at app//org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:138)
	at app//org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at app//org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:80)
	at app//org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at app//org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at app//org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at app//org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at app//org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at app//org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
	at app//org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at app//org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at app//org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at app//org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
	at app//com.sun.proxy.$Proxy164.findRelatedRegistryNodesByDrivingLicense(Unknown Source)
	at app//com.tlt.quantum.registry.repository.AliasRelationsRepositoryTest.findRelatedRegistryNodesByDrivingLicense(AliasRelationsRepositoryTest.java:94)
	at java.base@15.0.6/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@15.0.6/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base@15.0.6/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@15.0.6/java.lang.reflect.Method.invoke(Method.java:564)
	at app//org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at app//org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at app//org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at app//org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at app//org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at app//org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at app//org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at app//org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at app//org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at app//org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base@15.0.6/java.util.ArrayList.forEach(ArrayList.java:1511)
	at app//org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at app//org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base@15.0.6/java.util.ArrayList.forEach(ArrayList.java:1511)
	at app//org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at app//org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at app//org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at app//org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at app//org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at java.base@15.0.6/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@15.0.6/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base@15.0.6/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@15.0.6/java.lang.reflect.Method.invoke(Method.java:564)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy5.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: org.springframework.data.mapping.model.MappingInstantiationException: Failed to instantiate com.tlt.quantum.keymapper.model.node.AbstractNodeEntity using constructor public com.tlt.quantum.keymapper.model.node.AbstractNodeEntity() with arguments 
	at app//org.springframework.data.mapping.model.ClassGeneratingEntityInstantiator$MappingInstantiationExceptionEntityInstantiator.createInstance(ClassGeneratingEntityInstantiator.java:321)
	at app//org.springframework.data.mapping.model.ClassGeneratingEntityInstantiator.createInstance(ClassGeneratingEntityInstantiator.java:89)
	at app//org.springframework.data.neo4j.core.mapping.DefaultNeo4jEntityConverter.instantiate(DefaultNeo4jEntityConverter.java:460)
	at app//org.springframework.data.neo4j.core.mapping.DefaultNeo4jEntityConverter.lambda$map$3(DefaultNeo4jEntityConverter.java:277)
	at app//org.springframework.data.neo4j.core.mapping.DefaultNeo4jEntityConverter.map(DefaultNeo4jEntityConverter.java:295)
	at app//org.springframework.data.neo4j.core.mapping.DefaultNeo4jEntityConverter.map(DefaultNeo4jEntityConverter.java:250)
	at app//org.springframework.data.neo4j.core.mapping.DefaultNeo4jEntityConverter.read(DefaultNeo4jEntityConverter.java:112)
	... 121 more
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.tlt.quantum.keymapper.model.node.AbstractNodeEntity]: Class is abstract
	... 128 more

```


In the database I only have Node labeled as `License` but it still tried to initialize the abstract class. I might create a separate bug issue with isolated code if the above example is expected to work.

**Comment by meistermeier** [comment]
But this could not work if your repository is a `AbstractNodeEntity` repository. Because _officially_ this is not a mapped node type/label (as you want it) but on the other hand you cannot expect SDN to treat it like a valid node entity by using it as the repository's type.
A separated issue report would be good to have. Even if it is clarification and maybe more tests for SDN.
Thanks.

**Comment by aleksanderlech** [comment]
Hey,

But whats the difference between my case and the one you have in your tests?


```
public abstract class AbstractPet {

	@Id
	@GeneratedValue
	private Long id;

	@Getter @Setter
	private String name;

}
```

```
@Node(labels = "Cat")
public class Cat extends AbstractPet {

}

```

```
interface PetsRepository extends Neo4jRepository<AbstractPet, Long> {

		@Query("MATCH (n {name: $name}) RETURN n")
		List<AbstractPet> findPets(@Param("name") String name);

}
```

**Comment by meistermeier** [comment]
Could you please tell me which version of SDN you are currently trying to upgrade to?
I assume that you no longer do the 6.0.x migration but more something like 6.1.x or even better 6.2.x, right? There were a lot of improvements.
I am happy to create a reproducer based on your version and we can work out the differences between your application and mine then.
Also please be aware that you would need the labels for the higher classes if you make use of generated queries. They add all labels from the hierarchy regardless if there is any annotation missing or not.

**Comment by aleksanderlech** [comment]
Hello, it was Spring Boot 2.6.3 so it's spring-data-neo4j:6.2.1.
