### ISSUE TITLE
IllegalArgumentException when loading CustomQueries and Custom DTOs

### ISSUE THREAD

**Issue by gsviteri** [spring-projects/spring-data-neo4j#2217]
Hi devs,

I am running a custom query that is supposed to be mapped to one Custom DTO. See...

```java
    public Collection<DoiPathwayDTO> doiPathwayDTO() {
        String query =
                "MATCH (p:Pathway) " +
                        "WHERE EXISTS(p.doi) " +
                        "OPTIONAL MATCH (p)<-[:revised]-(re:InstanceEdit) " +
                        "OPTIONAL MATCH (p)<-[:authored | revised]-(:InstanceEdit)<-[:author]-(patrs:Person) " +
                        "OPTIONAL MATCH (p)<-[:reviewed]-(:InstanceEdit)<-[:author]-(prvwd:Person) " +
                        "OPTIONAL MATCH (p)<-[:edited]-(:InstanceEdit)<-[:author]-(pedtd:Person) " +
                        "OPTIONAL MATCH (p)-[:hasEvent*]->(e:Event) " +
                        "OPTIONAL MATCH (e)<-[:authored]-(:InstanceEdit)<-[:author]-(rlea:Person) " +
                        "OPTIONAL MATCH (e)<-[:reviewed]-(:InstanceEdit)<-[:author]-(rler:Person) " +
                        "OPTIONAL MATCH (e)<-[:edited]-(:InstanceEdit)<-[:author]-(rlee:Person) " +
                        "WITH COLLECT(DISTINCT patrs) + COLLECT(distinct rlea) AS allAuthors, " +
                        "COLLECT(DISTINCT prvwd) + COLLECT(distinct rler) AS allReviewers, " +
                        "COLLECT(DISTINCT pedtd) + COLLECT(distinct rlee) AS allEditors, p, re " +
                        "UNWIND (CASE allAuthors WHEN [] THEN [null] ELSE allAuthors END) AS totalAtrs " +
                        "UNWIND (CASE allReviewers WHEN [] THEN [null] ELSE allReviewers END) AS totalRvwd " +
                        "UNWIND (CASE allEditors WHEN [] THEN [null] ELSE allEditors END) AS totalEdtd " +
                        "RETURN p.displayName AS displayName, " +
                        "       p.doi AS doi, " +
                        "       p.stId AS stId, " +
                        "       p.speciesName AS species, " +
                        "       p.releaseDate AS releaseDate, " +
                        "       p.releaseStatus AS releaseStatus, " +
                        "       MAX(re.dateTime) AS reviseDate " +
                        "       COLLECT(DISTINCT totalAtrs) AS authors, " +
                        "       COLLECT(DISTINCT totalRvwd) AS reviewers, " +
                        "       COLLECT(DISTINCT totalEdtd) AS editors " +
                        "ORDER BY toLower(p.displayName) LIMIT 1 ";   // LIMIT 1 added for testing purpose, >400 rows expected


// Same error
// Collection<DoiPathwayDTO> all =  neo4jClient.query(query).fetchAs(DoiPathwayDTO.class).all();

        PreparedQuery<DoiPathwayDTO> pp = PreparedQuery.queryFor(DoiPathwayDTO.class).withCypherQuery(query).withParameters(Collections.EMPTY_MAP).build();
        Optional<DoiPathwayDTO> _ret = neo4jTemplate.toExecutableQuery(pp).getSingleResult();

        return _ret;

    }
```

```java
public class DoiPathwayDTO {
    @Id private Long id;
    private String displayName;
    private String doi;
    private String stId;
    private String species;
    private String releaseDate;
    private String reviseDate;
    private String releaseStatus;
    private Collection<Person> authors;
    private Collection<Person> reviewers;
    private Collection<Person> editors;

    public DoiPathwayDTO() {
    }
   // getters and setters
```

After running it throws expection

```
16:52:00.217 [main] DEBUG o.s.d.n.r.config.StartupLogger - Bootstrapping imperative Neo4j repositories based on SDN v6.1.0-RC1 with Spring Data Commons v2.5.0-RC1 and Neo4j Driver v4.2.3-10da2e22eb41fdc447ddfd98f341fe0efc2fdb07.

16:52:16.154 [main] DEBUG o.springframework.data.neo4j.cypher - Executing:
MATCH (p:Pathway) WHERE EXISTS(p.doi) OPTIONAL MATCH (p)<-[:revised]-(re:InstanceEdit) OPTIONAL MATCH (p)<-[:authored | revised]-(:InstanceEdit)<-[:author]-(patrs:Person) OPTIONAL MATCH (p)<-[:reviewed]-(:InstanceEdit)<-[:author]-(prvwd:Person) OPTIONAL MATCH (p)<-[:edited]-(:InstanceEdit)<-[:author]-(pedtd:Person) OPTIONAL MATCH (p)-[:hasEvent*]->(e:Event) OPTIONAL MATCH (e)<-[:authored]-(:InstanceEdit)<-[:author]-(rlea:Person) OPTIONAL MATCH (e)<-[:reviewed]-(:InstanceEdit)<-[:author]-(rler:Person) OPTIONAL MATCH (e)<-[:edited]-(:InstanceEdit)<-[:author]-(rlee:Person) WITH COLLECT(DISTINCT patrs) + COLLECT(distinct rlea) AS allAuthors, COLLECT(DISTINCT prvwd) + COLLECT(distinct rler) AS allReviewers, COLLECT(DISTINCT pedtd) + COLLECT(distinct rlee) AS allEditors, p, re UNWIND (CASE allAuthors WHEN [] THEN [null] ELSE allAuthors END) AS totalAtrs UNWIND (CASE allReviewers WHEN [] THEN [null] ELSE allReviewers END) AS totalRvwd UNWIND (CASE allEditors WHEN [] THEN [null] ELSE allEditors END) AS totalEdtd RETURN p.displayName AS displayName,        p.doi AS doi,        p.stId AS stId,        p.speciesName AS species,        p.releaseDate AS releaseDate,        p.releaseStatus AS releaseStatus,        MAX(re.dateTime) AS reviseDate ORDER BY toLower(p.displayName) LIMIT 1 


java.lang.IllegalArgumentException: Records with more than one value cannot be converted without a mapper.

	at org.springframework.data.neo4j.core.SingleValueMappingFunction.apply(SingleValueMappingFunction.java:52)
	at org.springframework.data.neo4j.core.SingleValueMappingFunction.apply(SingleValueMappingFunction.java:33)
	at org.springframework.data.neo4j.core.DefaultNeo4jClient$DefaultRecordFetchSpec.one(DefaultNeo4jClient.java:305)
	at java.base/java.util.Optional.flatMap(Optional.java:294)
	at org.springframework.data.neo4j.core.Neo4jTemplate$DefaultExecutableQuery.getSingleResult(Neo4jTemplate.java:826)
	at org.reactome.server.graph.repository.AdvancedDatabaseObjectRepositoryNG.doiPathwayDTO(AdvancedDatabaseObjectRepositoryNG.java:150)
	at org.reactome.server.graph.repository.AdvancedDatabaseObjectRepositoryNG$$FastClassBySpringCGLIB$$fb06dab4.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
	at org.reactome.server.graph.repository.AdvancedDatabaseObjectRepositoryNG$$EnhancerBySpringCGLIB$$d926c22.doiPathwayDTO(<generated>)
	at org.reactome.server.graph.service.DoiServiceTest.getAllDoiPathway(DoiServiceTest.java:30)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
```

**Comment by meistermeier** [comment]
There are several things in there to discuss.
Let's start with the error message: `Records with more than one value cannot be converted without a mapper.` This means that the query results in multiple records (fields). Because you are returning multiple fields intentionally, the error message is expected to happen in this case. Spring Data Neo4j does not know how to put those "arbitrary" fields into a concrete entity class without any hints (1) or custom mapping function (2).
1. To be sure what to map, SDN needs some meta-information from the database like labels, identifier but also relationships, not only the related nodes. With just the fields and related nodes coming from the database, this is not enough. Returning the (root) node directly like described in the documentation https://docs.spring.io/spring-data/neo4j/docs/current/reference/html/#custom-queries might already help. Because I noticed the `MAX(re.dateTime) AS reviseDate` this would have limitations with just pure nodes. You could fake the returned data that it looks like the result of a generated query (map projection) like here https://docs.spring.io/spring-data/neo4j/docs/current/reference/html/#query-creation.load but this would make the return part of the query more complex.
2. The main reason why you are facing this error message is, that -assuming the `DoiPathwayDTO` is properly registered as an entity- you are using the wrong API to fetch the data. A `Neo4jClient` (commented part) does not know anything about the domain's meta-data. The `Neo4jTemplate` provides convenience functionality like `neo4jTemplate.findAll(query, DoiPathwayDTO.class)` to ensure that the generic mapping function that works with the meta-data gets called. But even with this you would end up in 1. again because the returned data does provide all information.

In the end you have two options here: Either tuning the result part of the query and using the `findAll` (or similar) API to make SDN think that this is a valid node (and valid relationship and related nodes)
OR
Using the `Neo4jClient` (because there is no need to use the template here) and writing your own mapping function e.g.
```
client.query(query).fetchAs(DoiPathwayDTO.class).mappedBy((ts, record) -> {
	// custom mapping code 
	return new DoiPathwayDTO(....);
}).all()
```

**Comment by gsviteri** [comment]
Thank you very much.  @meistermeier 

Excellent. So far happy with the second option of using Neo4jClient and writing my own mapping function.
Minor issue: The value after mapping are "double quoted" - see attachment, please.
![image](https://user-images.githubusercontent.com/6883670/114419918-c0207e80-9bab-11eb-903e-f9138602d3dc.png)

Thank you!

**Comment by meistermeier** [comment]
Glad to hear this: Because you have now Neo4j Java Driver types in your hand, you should use the driver's conversion function like `asString()` / `asLong()` / ... as needed to get the correct value.

**Comment by meistermeier** [comment]
Just adding the edit as a new message to notify you: https://neo4j.com/docs/api/java-driver/4.2/org/neo4j/driver/Value.html
