### ISSUE TITLE
DatabaseSelection is not allways used

### ISSUE THREAD

**Issue by VladoKuruc** [spring-projects/spring-data-neo4j#2234]
After upgrade to SDN 6.1.0 I have Issue with DatabaseSelection.

I use an existing database for unit tests, so I do not create a database in them. I just need to clean up the data at the beginning of the transaction and with the rollback at the end so that testing does not affect the existing data.

In version 6.0.x, I had to use the .in(databaseName) clause.

`neo4jClient.query("MATCH (n) DETACH DELETE n").in("neo4jtest").run();`

DatabaseSelectionProvider is now available in version 6.1.x in neo4jClient, so it would be nice not to use it.
In this case, an error occurs.

`java.lang.IllegalStateException: There is already an ongoing Spring transaction for 'neo4jtest', but you request the default database`

However, the same error occurs in the case of a more complex mapping during repository.save () in a transaction where I cannot influence it.
Take a look at the attached unittest where I use the modified AltHobby class. I added two properties there.

[DatabaseSelectionProviderIT.java.txt](https://github.com/spring-projects/spring-data-neo4j/files/6324386/DatabaseSelectionProviderIT.java.txt)

```java
	@Relationship(type = "CHILD", direction = Relationship.Direction.INCOMING)
	private List<AltHobby> memberOf = new ArrayList<>();

	@Relationship(type = "CHILD", direction = Relationship.Direction.OUTGOING)
	private List<AltHobby> childs = new ArrayList<>(); 

	public List<AltHobby> getMemberOf() {
		return memberOf;
	}
	
	public List<AltHobby> getChilds() {
		return childs;
	} 
```
Thank for investigation.

**Comment by meistermeier** [comment]
Many thanks for reporting this. There seems to be one code path that does not take the `DatabaseSelectionProvider` into consideration.

**Comment by meistermeier** [comment]
There should be now a snapshot be available: `6.1.1-GH-2234-SNAPSHOT` with a (first) solution.

**Comment by VladoKuruc** [comment]
Thank you very much for the quick solution.
The mentioned unit test is already passing. Also my real test with a more complex model. 
But I have another issue not directly related to this. If I have Set instead of List relationships, I get an error
`java.lang.ClassCastException: Cannot cast java.util.ArrayList to java.util.Set
	at java.lang.invoke.MethodHandleImpl.newClassCastException(MethodHandleImpl.java:361)
	at java.lang.invoke.MethodHandleImpl.castReference(MethodHandleImpl.java:356)
	at org.springframework.data.neo4j.integration.shared.common.AltHobby_Accessor_6ib4k1.setProperty(Unknown Source)
	at org.springframework.data.mapping.model.InstantiationAwarePropertyAccessor.setProperty(InstantiationAwarePropertyAccessor.java:104)
	at org.springframework.data.neo4j.core.RelationshipHandler.applyFinalResultToOwner(RelationshipHandler.java:130)
	at org.springframework.data.neo4j.core.Neo4jTemplate.lambda$processNestedRelations$24(Neo4jTemplate.java:730)
	at org.springframework.data.mapping.model.BasicPersistentEntity.doWithAssociations(BasicPersistentEntity.java:387)
	at org.springframework.data.neo4j.core.Neo4jTemplate.processNestedRelations(Neo4jTemplate.java:597)
	at org.springframework.data.neo4j.core.Neo4jTemplate.processRelations(Neo4jTemplate.java:588)
	at org.springframework.data.neo4j.core.Neo4jTemplate.saveImpl(Neo4jTemplate.java:352)
	at org.springframework.data.neo4j.core.Neo4jTemplate.save(Neo4jTemplate.java:289)
	at org.springframework.data.neo4j.repository.support.SimpleNeo4jRepository.save(SimpleNeo4jRepository.java:117)
`
I'll add a unit test later.

**Comment by michael-simons** [comment]
Thanks @VladoKuruc I'll take care of the 2nd issue: https://github.com/spring-projects/spring-data-neo4j/issues/2236

**Comment by meistermeier** [comment]
Thanks for your valuable feedback.
