### ISSUE TITLE
Spatial Index throws exception when querying against a node that was removed.

### ISSUE THREAD

**Issue by Infiniverse** [spring-projects/spring-data-neo4j#226]
Spring Data Neo4j throws and exception when doing a spatial query against a node that has been deleted. Note sure if it's a Spring Data Neo4j issue, or a neo4j-spatial issue.

The following test, added to SpatialGraphRepositoryTests.java fails:

```@Test
public void testFindPeopleWithinBoundingBoxAfterNodeRemoved() {
        personRepository.delete(testTeam.david);
        Iterable<Person> teamMembers = personRepository.findWithinBoundingBox("personLayer", 55, 15, 57, 17);
        assertThat(asCollection(teamMembers), hasItems(testTeam.michael));
}
```

The thrown exception is:

```
testFindPeopleWithinBoundingBoxRemoved(org.springframework.data.neo4j.repository.SpatialGraphRepositoryTests)  Time elapsed: 0.22 sec  <<< ERROR!
java.lang.IllegalStateException: No primary SDN label exists .. (i.e one starting with _) 
	at org.springframework.data.neo4j.support.typerepresentation.LabelBasedNodeTypeRepresentationStrategy.readAliasFrom(LabelBasedNodeTypeRepresentationStrategy.java:126)
	at org.springframework.data.neo4j.support.typerepresentation.LabelBasedNodeTypeRepresentationStrategy.readAliasFrom(LabelBasedNodeTypeRepresentationStrategy.java:39)
	at org.springframework.data.neo4j.support.mapping.TRSTypeAliasAccessor.readAliasFrom(TRSTypeAliasAccessor.java:36)
	at org.springframework.data.neo4j.support.mapping.TRSTypeAliasAccessor.readAliasFrom(TRSTypeAliasAccessor.java:26)
	at org.springframework.data.convert.DefaultTypeMapper.readType(DefaultTypeMapper.java:102)
	at org.springframework.data.convert.DefaultTypeMapper.getDefaultedTypeToBeUsed(DefaultTypeMapper.java:165)
	at org.springframework.data.convert.DefaultTypeMapper.readType(DefaultTypeMapper.java:142)
	at org.springframework.data.neo4j.support.mapping.Neo4jEntityConverterImpl.read(Neo4jEntityConverterImpl.java:78)
	at org.springframework.data.neo4j.support.mapping.Neo4jEntityPersister$CachedConverter.read(Neo4jEntityPersister.java:170)
	at org.springframework.data.neo4j.support.mapping.Neo4jEntityPersister.createEntityFromState(Neo4jEntityPersister.java:189)
	at org.springframework.data.neo4j.support.Neo4jTemplate.createEntityFromState(Neo4jTemplate.java:224)
	at org.springframework.data.neo4j.repository.LegacyIndexSearcher.createEntity(LegacyIndexSearcher.java:47)
	at org.springframework.data.neo4j.repository.LegacyIndexSearcher.access$000(LegacyIndexSearcher.java:21)
	at org.springframework.data.neo4j.repository.LegacyIndexSearcher$IndexHitsWrapper.underlyingObjectToObject(LegacyIndexSearcher.java:60)
	at org.springframework.data.neo4j.repository.LegacyIndexSearcher$IndexHitsWrapper.underlyingObjectToObject(LegacyIndexSearcher.java:50)
	at org.neo4j.helpers.collection.IterableWrapper$MyIteratorWrapper.underlyingObjectToObject(IterableWrapper.java:57)
	at org.neo4j.helpers.collection.IteratorWrapper.next(IteratorWrapper.java:47)
	at org.neo4j.helpers.collection.IteratorUtil.addToCollection(IteratorUtil.java:382)
	at org.neo4j.helpers.collection.IteratorUtil.addToCollection(IteratorUtil.java:461)
	at org.neo4j.helpers.collection.IteratorUtil.asCollection(IteratorUtil.java:560)
	at org.springframework.data.neo4j.repository.SpatialGraphRepositoryTests.testFindPeopleWithinBoundingBoxRemoved(SpatialGraphRepositoryTests.java:100)
```

This failure was seen with SDN 3.2.1

**Comment by stephaneeybert** [comment]
I'm seeing something similar in SDN 3.3.2 against a Neo4j neo4j-community-2.2.4 and I posted in at http://stackoverflow.com/questions/32591178/deleting-a-neo4j-node-from-a-spring-application

**Comment by mangrish** [comment]
Closed. Issue out of date.
