### ISSUE TITLE
Return multiple values as class parameters

### ISSUE THREAD

**Issue by alxxyz** [spring-projects/spring-data-neo4j#2266]
```
@Query("MATCH (:User {id: $userId})-[relationshipValue:PARTNER|FRIEND]-(user) RETURN user, relationshipValue")
Page<RelationshipEntity> findAll(String userId);
```
```
@Node("User)
public class UserEntity {
    @Id
    private String id;
    private String name;
    // getters and setters
}
public class RelationshipEntity {
    private UserEntity user;
    private RelationshipValue relationshipValue;
    // getters and setters
}
```
It can not map result to `RelationshipEntity`
```
org.springframework.data.neo4j.core.mapping.NoRootNodeMappingException: Could not find mappable nodes or relationships inside Record<{user: node<1>, relationshipValue: relationship<0>}> for org.springframework.data.neo4j.core.mapping.DefaultNeo4jPersistentEntity@71cf3b96
	at org.springframework.data.neo4j.core.mapping.DefaultNeo4jEntityConverter.read(DefaultNeo4jEntityConverter.java:102) ~[spring-data-neo4j-6.0.5.jar:6.0.5]
	at org.springframework.data.neo4j.core.mapping.DefaultNeo4jEntityConverter.read(DefaultNeo4jEntityConverter.java:65) ~[spring-data-neo4j-6.0.5.jar:6.0.5]
	at org.springframework.data.neo4j.core.mapping.Schema.lambda$getRequiredMappingFunctionFor$0(Schema.java:96) ~[spring-data-neo4j-6.0.5.jar:6.0.5]
	at org.springframework.data.neo4j.core.PreparedQuery$AggregatingMappingFunction.apply(PreparedQuery.java:233) ~[spring-data-neo4j-6.0.5.jar:6.0.5]
	at org.springframework.data.neo4j.core.PreparedQuery$AggregatingMappingFunction.apply(PreparedQuery.java:153) ~[spring-data-neo4j-6.0.5.jar:6.0.5]
	at org.springframework.data.neo4j.core.DelegatingMappingFunctionWithNullCheck.apply(DelegatingMappingFunctionWithNullCheck.java:45) ~[spring-data-neo4j-6.0.5.jar:6.0.5]
	at org.springframework.data.neo4j.core.DelegatingMappingFunctionWithNullCheck.apply(DelegatingMappingFunctionWithNullCheck.java:35) ~[spring-data-neo4j-6.0.5.jar:6.0.5]
	at org.springframework.data.neo4j.core.DefaultNeo4jClient$DefaultRecordFetchSpec.one(DefaultNeo4jClient.java:284) ~[spring-data-neo4j-6.0.5.jar:6.0.5]
```

How to return multiple values as class parameters?
We need to retrieve all the friends & partners, and to know the relationship

**Comment by meistermeier** [comment]
You would set up your domain class like this
```
@Node("User)
public class UserEntity {
    @Id
    private String id;
    private String name;

   @Relationship("FRIEND")
    private List<UserEntity> friends;
   @Relationship("PARTNER")
    private List<UserEntity> partners;

    // getters and setters
}
```
And use the offered method `repository.findById(userId)`.
This will
a) generate the right query for you
and
b) create the matching `UserEntity` instance with all friends and partners attached.

Please also have a look at the reference documentation https://docs.spring.io/spring-data/neo4j/docs/current/reference/html/#reference

For further questions I would like to ask you to reach out either at StackOverflow (https://stackoverflow.com/questions/tagged/spring-data-neo4j) or Neo4j's Discourse (https://community.neo4j.com/c/drivers-stacks/spring-data-neo4j-ogm/30)

**Comment by alxxyz** [comment]
What about pagination, if we need to retrieve only 10 of friends or partners?

**Comment by meistermeier** [comment]
You won't paginate a list in a mapped object.
But for completeness:
```
@Query(
value = "MATCH (n:User {id: $userId})-[r:PARTNER|FRIEND]-(user) RETURN user, collect(r), collect(n) ORDER BY user.name ASC SKIP $skip LIMIT $limit", 
countQuery = "MATCH (n:User {id: $userId})-[r:PARTNER|FRIEND]-(user) RETURN count(user)"
)
Page<User> findAll(String userId);
```
^^ not tested but this should return all related `Users` with one connection to the user with the given _userId_.
Please have a look at https://docs.spring.io/spring-data/neo4j/docs/current/reference/html/#faq.custom-queries-with-page-and-slice for a more detailed explanation of pagination queries.
