### ISSUE TITLE
Track state of objects with assigned ids correctly.

### ISSUE THREAD

**Issue by LGDOI** [spring-projects/spring-data-neo4j#2347]
I cannot tell if is a bug or a feature.

Given two node classes `Application` and `Workflow`. `Application` has outgoing 1-to-many relationship to `Workflow`. 
`Workflow` has incoming relationship to `Application`.

The following code causes NPE during `.saveAll` call.

```kotlin
  @Test
  fun npe() {
    val app1 = Application()
    val wf1 = Workflow()
    val wf2 = Workflow()

    wf1.application = app1 // <===== Comment out to avoid NPE
    wf2.application = app1 // <===== Comment out to avoid NPE

    app1.workflows = listOf(wf1, wf2)
    applicationRepository.saveAll(listOf(app1))
  }
```
Note: if you comment out these two lines setting app1 to wf1 and wf2, NPE won't occur.
Note2: replace `.saveAll(listOf(app1))` with `.save(app1)` solves the problem.
Note3: this example only shows one app1. but the same NPE happens even if the list size > 1

## Stacktrace
```
java.lang.NullPointerException
	at org.springframework.data.neo4j.core.mapping.NestedRelationshipProcessingStateMachine$RelationshipDescriptionWithSourceId.equals(NestedRelationshipProcessingStateMachine.java:133)
	at java.base/java.util.HashMap.putVal(HashMap.java:630)
	at java.base/java.util.HashMap.put(HashMap.java:607)
	at java.base/java.util.HashSet.add(HashSet.java:220)
	at org.springframework.data.neo4j.core.mapping.NestedRelationshipProcessingStateMachine.markRelationshipAsProcessed(NestedRelationshipProcessingStateMachine.java:154)
	at org.springframework.data.neo4j.core.Neo4jTemplate.lambda$processNestedRelations$25(Neo4jTemplate.java:772)
	at org.springframework.data.mapping.model.BasicPersistentEntity.doWithAssociations(BasicPersistentEntity.java:387)
	at org.springframework.data.neo4j.core.Neo4jTemplate.processNestedRelations(Neo4jTemplate.java:658)
	at org.springframework.data.neo4j.core.Neo4jTemplate.lambda$processNestedRelations$25(Neo4jTemplate.java:801)
	at org.springframework.data.mapping.model.BasicPersistentEntity.doWithAssociations(BasicPersistentEntity.java:387)
	at org.springframework.data.neo4j.core.Neo4jTemplate.processNestedRelations(Neo4jTemplate.java:658)
	at org.springframework.data.neo4j.core.Neo4jTemplate.processRelations(Neo4jTemplate.java:649)
	at org.springframework.data.neo4j.core.Neo4jTemplate.lambda$saveAllImpl$14(Neo4jTemplate.java:482)
... more
```

## Analysis

`Neo4jTemplate.processNestedRelations` contains a lambda there is a condition to set  `relatedInternalId` on line 746-747.

```
if (stateMachine.hasProcessedValue(relatedValueToStore)) {
  relatedInternalId = stateMachine.getInternalId(relatedValueToStore);
```

When this condition is `true`, `stateMachine.getInternalId(relatedValueToStore);` return `null`. 

## Question

Should this condition return `false` if the `stateMachine` does not have an internal ID for `relatedValueToStore`?

**Comment by michael-simons** [comment]
Hi @LGDOI Are you able to share the classes for `Application` and `Workflow`? I am not able to reproduce this.

Also are you using 6.1.x or 6.0.x?

**Comment by michael-simons** [comment]
Never mind, I could figure out what I needed to reproduce it from your other ticket.

**Comment by LGDOI** [comment]
Hi, @michael-simons, 
Thank you for looking into this. So, this issue is related to other issue and will be fixed as part of other bug fix?

I believe I was on 6.1.3 when I saw this error (99.9%). But 0.1% chance I was on older version as I was switching b/w version to compare the API behavior.

**Comment by michael-simons** [comment]
You're welcome and sorry for any inconvenience. Both reports have been very useful to us.
