### ISSUE TITLE
ChannelErrorHandler: Connection reset by peer

### ISSUE THREAD

**Issue by alxxyz** [spring-projects/spring-data-neo4j#2357]
For unknown reasons sometimes we receive this exeception
```
WARN 1 --- [o4jDriverIO-2-6] org.neo4j.driver.ChannelErrorHandler     : [0x65894c7c][host:7687][bolt-90] Fatal error occurred in the pipeline
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.8.0_212]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.8.0_212]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_212]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_212]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_212]
	at org.neo4j.driver.internal.shaded.io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
	at org.neo4j.driver.internal.shaded.io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1133) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
	at org.neo4j.driver.internal.shaded.io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) [neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) [neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) [neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
	at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
	at org.neo4j.driver.internal.shaded.io.netty.ut
```
What can be the issue?

**Comment by michael-simons** [comment]
This is an exception of the Neo4j Java driver we are using. You might want to reopen it there https://github.com/neo4j/neo4j-java-driver/issues, I cannot transfer this issue.
