### ISSUE TITLE
In custom query,  it is error when use  parameter in relationship depth syntax(**[r*$minRingLevel..$maxRingLevel]**)

### ISSUE THREAD

**Issue by liseri** [spring-projects/spring-data-neo4j#2586]
## Issue
In custom query,  it is error when use  parameter in relationship depth syntax(**[r*$minRingLevel..$maxRingLevel]**), like this:
```
//the whole code as below.
@Query(value = """
            match p=(s:hktxjm)-[r*$minRingLevel..$maxRingLevel]->(s:hktxjm)
```

## Error
```
"match p=(s:hktxjm)-[r*$minRingLevel..$maxRingLevel]->(s:hktxjm)"
                                    ^; Error code 'Neo.ClientError.Statement.SyntaxError'; nested exception is org.neo4j.driver.exceptions.ClientException: Invalid input '..': expected "]" (line 1, column 36 (offset: 35))
"match p=(s:hktxjm)-[r*$minRingLevel..$maxRingLevel]->(s:hktxjm)"
                                    ^] with root cause

org.neo4j.driver.exceptions.ClientException: Invalid input '..': expected "]" (line 1, column 36 (offset: 35))
"match p=(s:hktxjm)-[r*$minRingLevel..$maxRingLevel]->(s:hktxjm)"
                                    ^
	at org.neo4j.driver.internal.util.Futures.blockingGet(Futures.java:111)
	at org.neo4j.driver.internal.InternalTransaction.run(InternalTransaction.java:58)
	at org.neo4j.driver.internal.AbstractQueryRunner.run(AbstractQueryRunner.java:34)
	at org.neo4j.driver.internal.AbstractQueryRunner.run(AbstractQueryRunner.java:39)
	at org.springframework.data.neo4j.core.DefaultNeo4jClient$DelegatingQueryRunner.run(DefaultNeo4jClient.java:146)
	at org.springframework.data.neo4j.core.DefaultNeo4jClient$RunnableStatement.runWith(DefaultNeo4jClient.java:218)
	at org.springframework.data.neo4j.core.DefaultNeo4jClient$DefaultRecordFetchSpec.all(DefaultNeo4jClient.java:485)
	at java.base/java.util.Optional.map(Optional.java:260)
	at org.springframework.data.neo4j.core.Neo4jTemplate$DefaultExecutableQuery.getResults(Neo4jTemplate.java:1020)
	at org.springframework.data.neo4j.repository.query.Neo4jQueryExecution$DefaultQueryExecution.execute(Neo4jQueryExecution.java:51)
	at org.springframework.data.neo4j.repository.query.AbstractNeo4jQuery.execute(AbstractNeo4jQuery.java:94)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:137)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:121)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:160)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:139)
```

## Code
**It is error**
```
@Transactional(readOnly = true)
    @Query(value = """
            match p=(s:hktxjm)-[r*$minRingLevel..$maxRingLevel]->(s:hktxjm)
            where s.model = $model
            return s, collect(nodes(p)), collect(relationships(p))
            """,
            countQuery = """
            match p=(s:hktxjm)-[r*$minRingLevel..$maxRingLevel]->(s:hktxjm)
            where s.model = $model
            return count(s)
            """
    )
    Page<TxjmNodeEntity> queryRings(@Param("model") String model, @Param("minRingLevel") Integer minRingLevel, @Param("maxRingLevel") Integer maxRingLevel, Pageable pageable);
```

**But It is normal**
```
@Transactional(readOnly = true)
    @Query(value = """
            match p=(s:hktxjm)-[r*1..10]->(s:hktxjm)
            where s.model = $model
            return s, collect(nodes(p)), collect(relationships(p))
            """,
            countQuery = """
            match p=(s:hktxjm)-[r*1..10]->(s:hktxjm)
            where s.model = $model
            return count(s)
            """
    )
    Page<TxjmNodeEntity> queryRings(@Param("model") String model, @Param("minRingLevel") Integer minRingLevel, @Param("maxRingLevel") Integer maxRingLevel, Pageable pageable);
```

**Comment by meistermeier** [comment]
Hi and thanks for raising this.
Unfortunately, path depths are not supported as parameters in Cypher. Given your custom query, `$minRingLevel` and `$maxRingLevel` will not get picked up as eligible parameters and just passed on to the database. This is why you are also facing the exception on `..` because the `$minRingLevel` gets interpreted as the relationship type.
Sorry that we cannot help you here.

**Comment by liseri** [comment]
Thank you ; I will try other method, for example template or client.

**Comment by meistermeier** [comment]
If you are thinking about creating the queries via a builder, try the cypher-dsl (https://github.com/neo4j-contrib/cypher-dsl)
