### ISSUE TITLE
Optimistic locking mechanism "cascading" through relationships

### ISSUE THREAD

**Issue by zsoltkatona** [spring-projects/spring-data-neo4j#2604]
I'd like to ask you a quick question that I wasn't able to figure out myself after days of googling and reading the SDN reference.

We have a class and a node label, let's call it Dog and in that class we model a relationship to another class/label called Person. A Dog has a single owner who is a Person, let's say. We first create a Person and then a Dog on which we set the owner to an existing Person. Nothing weird so far.

However when we add optimistic locking for both the Dog and the Person (using `@Version`) then we run into a problem: when we save the Dog, then the Person's version also gets incremented, though that object isn't changed. In fact, it's set in a similar way to this:

```
public void save(Dog dog) {
    DogGMO dogGMO = dogMapper.convert(dog);
    PersonGMO personGMO = personRepository.findById(dog.getPerson().getId());
    dogGMO.setPerson(personGMO);
    dogRepository.save(dogGMO);
}
```

The problem it causes is that if there are more users/threads creating Dogs, then many of them will receive an optimistic locking exception:

```
org.springframework.dao.OptimisticLockingFailureException: An entity with the required version does not exist.

at org.springframework.data.neo4j.core.Neo4jTemplate.saveRelatedNode(Neo4jTemplate.java:858)
at org.springframework.data.neo4j.core.Neo4jTemplate.lambda$processNestedRelations$27(Neo4jTemplate.java:768)
at org.springframework.data.mapping.model.BasicPersistentEntity.doWithAssociations(BasicPersistentEntity.java:387)
at org.springframework.data.neo4j.core.Neo4jTemplate.processNestedRelations(Neo4jTemplate.java:677)
at org.springframework.data.neo4j.core.Neo4jTemplate.processRelations(Neo4jTemplate.java:662)
at org.springframework.data.neo4j.core.Neo4jTemplate.saveImpl(Neo4jTemplate.java:406)
at org.springframework.data.neo4j.core.Neo4jTemplate.save(Neo4jTemplate.java:321)
at org.springframework.data.neo4j.repository.support.SimpleNeo4jRepository.save(SimpleNeo4jRepository.java:117)
...
```

My question is this: is there a way to prevent that the Person's version is incremented but still have the relationship modeled at the OGM level?

Couple things I already tried:
- I tried double-mapping (Person, ImmutablePerson) but 2 classes can't have the same `@Node("Person")` annotation, so this didn't work,
- I tried annotating the Dog's person field with `@ReadOnlyProperty`, but then the relationship is not persisted (which is what I expected, but I'm mentioning it anyway just for completeness),
- I tried `@Reference` instead of `@ReadOnlyProperty`, it doesn't seem to have any effect,
- I tried synchronizing the save(Dog dog) method, and this works, but our service is expected to run with multiple replicas, so that won't scale,
- I tried modeling the relationship with a separate class that is annotated with `@RelationshipProperties`, but the Person's version still gets incremented, i.e. that doesn't stop the cascading,
- I updated Spring Data Neo4j to 6.3.3, Spring Data Commons to 2.7.3 and the Neo4j Java driver to 4.4.9 (i.e. all latest and greatest), but these didn't help either, I get the same opt. lock exception.

I don't know if this is by design or it's rather a bug. If it's by design, then it would be beneficial to have an annotation that stops the cascading, i.e. marks the target node of a relationship as read-only (and every node and relationship starting from that target node potentially).

Any help is appreciated.

**Comment by sibethencourt** [comment]
I've found that same issue myself when trying to use projections to save entities. Even if you create a projection that only changes the fields of the entity and the Id of the relationship it will increase the version of the related entity, even if it hasn't changed at all.

What we are doing so far to workaround it is to save the entity without relationships, and then use an ad-hoc cypher query to create only the relationships without modifying the version. This obviously is not ideal for many different reasons...

What we have tried as well, is to not use the queries created by sdn and just define ours to avoid the issue, we do this only in the most critical places to avoid any performance hit. 

Is this something that could be consider a bug? Since the ad-hoc queries are working very well, I'm considering how hard could it be to generate my own queries 🤷

**Comment by m4xs31f3rt** [comment]
We have run into pretty much exactly the same situation - we find that the original scenario describes our use-case perfectly well, and we also face the exact same behavior.

While we have invested quite some time into avoiding the issue at all (removing relationships where possible, attempting to remove "optimistic locking" completely and using explicit locking instead), we're still finding this troublesome and problematic at times.

Dear maintainers, this is a plus one on the overall issue.

@sibethencourt thank you for pointing towards "explicit ad-hoc query", because that is what we're about to do right now.

**Comment by shanon84** [comment]
I would like to fix this problem, but would like to discuss the best way to mark those relationships first:
Enhance the @Relationship annotation with a kind of cascadeType (ALL, CREATE)
Create on own annotation for it (like the @ReadOnlyProperty). For example @CascadeOnlyCreateProperty

In both ways:
if the object already exist: do not save the node or process the relationships.

**Comment by shanon84** [comment]
@michael-simons sorry to bother you, but I would realy like to have your opinion on my last posting.

**Comment by michael-simons** [comment]
No worries Torsten, you are not bothering us, but this is something we need to discuss with the team first. Thank you.

**Comment by michael-simons** [comment]
We are investigating this now https://github.com/spring-projects/spring-data-neo4j/commit/7678fab8719a29fa27e71c3a0e2f66e4232f1007#diff-4f8f57b79c28c8abbbdbfe2519f4aa636857897098716a0d3e3e4560078cc8f2R120

**Comment by shanon84** [comment]
@michael-simons I have a working solution now. Had it running in our big project and stopped all wrongfully updated related problems. I had no time to put it into github yet or put it under own tests (quickly added the files right now):
https://github.com/spring-projects/spring-data-neo4j/compare/main...shanon84:spring-data-neo4j:2604-cascading-support
I needed to update the code with the newest version of spring-data-neo4j, but the gist of it should be clear (and most likely still working).
Known "issues":
I use the internal logic to decide, if a node is to create or to update. If a related node does not have a @GeneratedValue annotation at his id property, the logic says it is always a new node -> still rewriting the related node.
But else it is working like a charm.

**Comment by michael-simons** [comment]
Just a ping that this will be released in 7.3 next week. Cheers.
