### ISSUE TITLE
Investigate random build failure on main

### ISSUE THREAD

**Issue by meistermeier** [spring-projects/spring-data-neo4j#2614]
This test failure pops up flaky on CI.
Cannot really tell right now why the additional interaction kicks in. Also not able to reproduce it in any way locally.

```
[ERROR] org.springframework.data.neo4j.core.ReactiveNeo4jClientTest.databaseSelectionShouldWorkAfterAsUser  Time elapsed: 0.116 s  <<< FAILURE!
org.mockito.exceptions.verification.NoInteractionsWanted: 

No interactions wanted here:
-> at org.springframework.data.neo4j.core.ReactiveNeo4jClientTest.verifyNoMoreInteractionsWithMocks(ReactiveNeo4jClientTest.java:100)
But found this interaction on mock 'record2':
-> at org.springframework.data.neo4j.core.DefaultReactiveNeo4jClient$DefaultRunnableSpec.lambda$fetch$0(DefaultReactiveNeo4jClient.java:275)
Actually, above is the only interaction with this mock.
	at org.springframework.data.neo4j.core.ReactiveNeo4jClientTest.verifyNoMoreInteractionsWithMocks(ReactiveNeo4jClientTest.java:100)

[ERROR] org.springframework.data.neo4j.core.ReactiveNeo4jClientTest.userSelectionShouldWork  Time elapsed: 0.008 s  <<< FAILURE!
org.mockito.exceptions.verification.NoInteractionsWanted: 

No interactions wanted here:
-> at org.springframework.data.neo4j.core.ReactiveNeo4jClientTest.verifyNoMoreInteractionsWithMocks(ReactiveNeo4jClientTest.java:100)
But found this interaction on mock 'record2':
-> at org.springframework.data.neo4j.core.DefaultReactiveNeo4jClient$DefaultRunnableSpec.lambda$fetch$0(DefaultReactiveNeo4jClient.java:275)
Actually, above is the only interaction with this mock.
	at org.springframework.data.neo4j.core.ReactiveNeo4jClientTest.verifyNoMoreInteractionsWithMocks(ReactiveNeo4jClientTest.java:100)

[ERROR] org.springframework.data.neo4j.core.ReactiveNeo4jClientTest.databaseSelectionShouldBePossibleOnlyOnce  Time elapsed: 0.009 s  <<< FAILURE!
org.mockito.exceptions.verification.NoInteractionsWanted: 

No interactions wanted here:
-> at org.springframework.data.neo4j.core.ReactiveNeo4jClientTest.verifyNoMoreInteractionsWithMocks(ReactiveNeo4jClientTest.java:100)
But found this interaction on mock 'record2':
-> at org.springframework.data.neo4j.core.DefaultReactiveNeo4jClient$DefaultRunnableSpec.lambda$fetch$0(DefaultReactiveNeo4jClient.java:275)
Actually, above is the only interaction with this mock.
	at org.springframework.data.neo4j.core.ReactiveNeo4jClientTest.verifyNoMoreInteractionsWithMocks(ReactiveNeo4jClientTest.java:100)

[ERROR] org.springframework.data.neo4j.core.ReactiveNeo4jClientTest.databaseSelectionShouldWorkBeforeAsUser  Time elapsed: 0.008 s  <<< FAILURE!
org.mockito.exceptions.verification.NoInteractionsWanted: 

No interactions wanted here:
-> at org.springframework.data.neo4j.core.ReactiveNeo4jClientTest.verifyNoMoreInteractionsWithMocks(ReactiveNeo4jClientTest.java:100)
But found this interaction on mock 'record2':
-> at org.springframework.data.neo4j.core.DefaultReactiveNeo4jClient$DefaultRunnableSpec.lambda$fetch$0(DefaultReactiveNeo4jClient.java:275)
Actually, above is the only interaction with this mock.
	at org.springframework.data.neo4j.core.ReactiveNeo4jClientTest.verifyNoMoreInteractionsWithMocks(ReactiveNeo4jClientTest.java:100)

```

**Comment by meistermeier** [comment]
Closing this now because it seems that this was just a hiccup and did not occur again (yet).
