### ISSUE TITLE
Cyclic reference with RelationshipProperties result in stackoverflow

### ISSUE THREAD

**Issue by bonelli** [spring-projects/spring-data-neo4j#2626]
I have a simple case in a Neo4j database with 2 entities linked with a relationship, and mapping the relationship on both entities with RelationshipProperties objects results in a StackOverflow.
I'm using version Spring Boot 2.7.5 - SDN 6.3.5 and the errors comes from a query performed through Spring Data Rest.

### Use case
This subset of classes is the one that reproduces my issue (some details omitted for brevity)
```
class Team {
    @Relationship(type = "TEAM_MEMBERSHIPS", direction = Direction.INCOMING)
    private List<PlayerMembership> members;
}

class Player {
    @Relationship(type = "TEAM_MEMBERSHIPS")
    private List<TeamMembership> teamMemberships;
}

@RelationshipProperties
class TeamMembership {
    @RelationshipId
    private Long id;

    @TargetNode
    private final Team team;

    LocalDate start;
    LocalDate end;
}

@RelationshipProperties
class PlayerMembership {
    @RelationshipId
    private Long id;

    @TargetNode
    private final Player player;

    LocalDate start;
    LocalDate end;
}
```

### Stacktrace
```
java.lang.StackOverflowError
	at org.springframework.core.convert.TypeDescriptor.getObjectType(TypeDescriptor.java:139)
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:186)
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:175)
	at org.springframework.data.neo4j.core.mapping.DefaultNeo4jConversionService.lambda$readValue$0(DefaultNeo4jConversionService.java:77)
	at org.springframework.data.neo4j.core.mapping.DefaultNeo4jConversionService.readValueImpl(DefaultNeo4jConversionService.java:103)
	at org.springframework.data.neo4j.core.mapping.DefaultNeo4jConversionService.readValue(DefaultNeo4jConversionService.java:84)
	at org.springframework.data.neo4j.core.mapping.DefaultNeo4jEntityConverter.lambda$populateFrom$4(DefaultNeo4jEntityConverter.java:509)
	at org.springframework.data.mapping.model.BasicPersistentEntity.doWithProperties(BasicPersistentEntity.java:368)
	at org.springframework.data.neo4j.core.mapping.PropertyHandlerSupport.doWithProperties(PropertyHandlerSupport.java:50)
	at org.springframework.data.neo4j.core.mapping.DefaultNeo4jEntityConverter.populateProperties(DefaultNeo4jEntityConverter.java:356)
	at org.springframework.data.neo4j.core.mapping.DefaultNeo4jEntityConverter.lambda$map$2(DefaultNeo4jEntityConverter.java:299)
	at org.springframework.data.neo4j.core.mapping.DefaultNeo4jEntityConverter.map(DefaultNeo4jEntityConverter.java:313)
	at org.springframework.data.neo4j.core.mapping.DefaultNeo4jEntityConverter.createInstanceOfRelationships(DefaultNeo4jEntityConverter.java:695)
	at org.springframework.data.neo4j.core.mapping.DefaultNeo4jEntityConverter.createInstanceOfRelationships(DefaultNeo4jEntityConverter.java:610)
	at org.springframework.data.neo4j.core.mapping.DefaultNeo4jEntityConverter.lambda$populateFrom$7(DefaultNeo4jEntityConverter.java:584)
	at org.springframework.data.neo4j.core.mapping.AssociationHandlerSupport.lambda$doWithAssociations$0(AssociationHandlerSupport.java:51)
	at org.springframework.data.mapping.model.BasicPersistentEntity.doWithAssociations(BasicPersistentEntity.java:395)
	at org.springframework.data.neo4j.core.mapping.AssociationHandlerSupport.doWithAssociations(AssociationHandlerSupport.java:49)
	at org.springframework.data.neo4j.core.mapping.DefaultNeo4jEntityConverter.populateProperties(DefaultNeo4jEntityConverter.java:363)
	at org.springframework.data.neo4j.core.mapping.DefaultNeo4jEntityConverter.lambda$map$2(DefaultNeo4jEntityConverter.java:299)
	at org.springframework.data.neo4j.core.mapping.DefaultNeo4jEntityConverter.map(DefaultNeo4jEntityConverter.java:313)
	at org.springframework.data.neo4j.core.mapping.DefaultNeo4jEntityConverter.createInstanceOfRelationships(DefaultNeo4jEntityConverter.java:695)
	at org.springframework.data.neo4j.core.mapping.DefaultNeo4jEntityConverter.createInstanceOfRelationships(DefaultNeo4jEntityConverter.java:610)
	at org.springframework.data.neo4j.core.mapping.DefaultNeo4jEntityConverter.lambda$populateFrom$7(DefaultNeo4jEntityConverter.java:584)
	at org.springframework.data.neo4j.core.mapping.AssociationHandlerSupport.lambda$doWithAssociations$0(AssociationHandlerSupport.java:51)
	at org.springframework.data.mapping.model.BasicPersistentEntity.doWithAssociations(BasicPersistentEntity.java:395)
	at org.springframework.data.neo4j.core.mapping.AssociationHandlerSupport.doWithAssociations(AssociationHandlerSupport.java:49)
	at org.springframework.data.neo4j.core.mapping.DefaultNeo4jEntityConverter.populateProperties(DefaultNeo4jEntityConverter.java:363)
	at org.springframework.data.neo4j.core.mapping.DefaultNeo4jEntityConverter.lambda$map$2(DefaultNeo4jEntityConverter.java:299)
	at org.springframework.data.neo4j.core.mapping.DefaultNeo4jEntityConverter.map(DefaultNeo4jEntityConverter.java:313)
	at org.springframework.data.neo4j.core.mapping.DefaultNeo4jEntityConverter.createInstanceOfRelationships(DefaultNeo4jEntityConverter.java:695)
	at org.springframework.data.neo4j.core.mapping.DefaultNeo4jEntityConverter.createInstanceOfRelationships(DefaultNeo4jEntityConverter.java:610)
	at org.springframework.data.neo4j.core.mapping.DefaultNeo4jEntityConverter.lambda$populateFrom$7(DefaultNeo4jEntityConverter.java:584)
	at org.springframework.data.neo4j.core.mapping.AssociationHandlerSupport.lambda$doWithAssociations$0(AssociationHandlerSupport.java:51)
.... goes on
```

**Comment by michael-simons** [comment]
Can you please share the missing details? 

Also
* Is it a read or write call?
* A dataset

Giving a dataset like this

```cypher
CREATE (t1:Team {id: randomUUID(), name: "T1"})
CREATE (t2:Team {id: randomUUID(), name: "T2"})
CREATE (p1:Player {id: randomUUID(), name: "P1"})
CREATE (p2:Player {id: randomUUID(), name: "P2"})
CREATE (p1) -[:TEAM_MEMBERSHIPS {start: date(), end: date() + duration({days: 23})}]->(t1)
CREATE (p2) -[:TEAM_MEMBERSHIPS {start: date(), end: date() + duration({days: 23})}]->(t1);
```

I can reliable read and write via repositories and templates. Please see the test here:

https://github.com/spring-projects/spring-data-neo4j/blob/2b20b26751329128439ebfbab06ef099c30f399e/src/test/java/org/springframework/data/neo4j/integration/issues/gh2626/GH2626IT.java#L72-L109

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
