### ISSUE TITLE
Asciidoctor build fails on linux

### ISSUE THREAD

**Issue by mp911de** [spring-projects/spring-data-neo4j#2653]
```
[ERROR] Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:2.1.0:process-asciidoc (html) on project spring-data-neo4j: Execution html of goal org.asciidoctor:asciidoctor-maven-plugin:2.1.0:process-asciidoc failed: An API incompatibility was encountered while executing org.asciidoctor:asciidoctor-maven-plugin:2.1.0:process-asciidoc: java.lang.UnsatisfiedLinkError: /home/jenkins/.sdkman/candidates/java/8.0.352-tem/jre/lib/amd64/libfontmanager.so: libfreetype.so.6: cannot open shared object file: No such file or directory
```

Not sure why this is the only build that fails. We can resort to local docs builds for the time being.

**Comment by mp911de** [comment]
Installing libfreetype improved the build but it fails now differently:

```
---------------------------------------------------
Exception in thread "main" java.lang.InternalError: java.lang.reflect.InvocationTargetException
	at sun.font.FontManagerFactory$1.run(sun/font/FontManagerFactory.java:87)
	at java.security.AccessController.doPrivileged(java/security/AccessController.java:318)
	at sun.font.FontManagerFactory.getInstance(sun/font/FontManagerFactory.java:75)
	at sun.font.SunFontManager.getInstance(sun/font/SunFontManager.java:248)
	at sun.font.FontDesignMetrics.getMetrics(sun/font/FontDesignMetrics.java:266)
	at sun.java2d.SunGraphics2D.getFontMetrics(sun/java2d/SunGraphics2D.java:863)
	at org.stathissideris.ascii2image.graphics.FontMeasurer.getAscent(org/stathissideris/ascii2image/graphics/FontMeasurer.java:80)
	at org.stathissideris.ascii2image.graphics.FontMeasurer$2.test(org/stathissideris/ascii2image/graphics/FontMeasurer.java:110)
	at org.stathissideris.ascii2image.graphics.FontMeasurer.deriveFont(org/stathissideris/ascii2image/graphics/FontMeasurer.java:124)
	at org.stathissideris.ascii2image.graphics.FontMeasurer.getFontFor(org/stathissideris/ascii2image/graphics/FontMeasurer.java:115)
	at org.stathissideris.ascii2image.graphics.Diagram.<init>(org/stathissideris/ascii2image/graphics/Diagram.java:493)
	at org.asciidoctor.diagram.ditaa.Ditaa.convertToImage(org/asciidoctor/diagram/ditaa/Ditaa.java:104)
	at org.asciidoctor.diagram.ditaa.Ditaa.doConvert(org/asciidoctor/diagram/ditaa/Ditaa.java:73)
	at org.asciidoctor.diagram.ditaa.Ditaa.generate(org/asciidoctor/diagram/ditaa/Ditaa.java:62)
	at org.asciidoctor.diagram.CommandProcessor.processRequest(org/asciidoctor/diagram/CommandProcessor.java:40)
	at org.asciidoctor.diagram.CommandProcessor.processRequest(org/asciidoctor/diagram/CommandProcessor.java:19)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(jdk/internal/reflect/NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(jdk/internal/reflect/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:568)
	at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:457)
	at org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:318)
	at RUBY.send_request(uri:classloader:/gems/asciidoctor-diagram-2.1.0/lib/asciidoctor-diagram/util/java_jruby.rb:27)
	at RUBY.convert(uri:classloader:/gems/asciidoctor-diagram-2.1.0/lib/asciidoctor-diagram/ditaa/converter.rb:85)
	at RUBY.create_image_block(uri:classloader:/gems/asciidoctor-diagram-2.1.0/lib/asciidoctor-diagram/diagram_processor.rb:170)
	at RUBY.process(uri:classloader:/gems/asciidoctor-diagram-2.1.0/lib/asciidoctor-diagram/diagram_processor.rb:86)
	at org.jruby.RubyMethod.call(org/jruby/RubyMethod.java:131)
	at org.jruby.RubyMethod$INVOKER$i$call.call(org/jruby/RubyMethod$INVOKER$i$call.gen)
	at RUBY.build_block(uri:classloader:/gems/asciidoctor-2.0.17/lib/asciidoctor/parser.rb:1053)
	at RUBY.next_block(uri:classloader:/gems/asciidoctor-2.0.17/lib/asciidoctor/parser.rb:904)
	at RUBY.next_section(uri:classloader:/gems/asciidoctor-2.0.17/lib/asciidoctor/parser.rb:397)
	at RUBY.next_section(uri:classloader:/gems/asciidoctor-2.0.17/lib/asciidoctor/parser.rb:382)
	at RUBY.next_section(uri:classloader:/gems/asciidoctor-2.0.17/lib/asciidoctor/parser.rb:382)
	at RUBY.next_section(uri:classloader:/gems/asciidoctor-2.0.17/lib/asciidoctor/parser.rb:387)
	at RUBY.parse(uri:classloader:/gems/asciidoctor-2.0.17/lib/asciidoctor/parser.rb:97)
	at RUBY.parse(uri:classloader:/gems/asciidoctor-2.0.17/lib/asciidoctor/document.rb:537)
	at RUBY.load(uri:classloader:/gems/asciidoctor-2.0.17/lib/asciidoctor/load.rb:84)
	at RUBY.convert(uri:classloader:/gems/asciidoctor-2.0.17/lib/asciidoctor/convert.rb:78)
	at RUBY.convert_file(uri:classloader:/gems/asciidoctor-2.0.17/lib/asciidoctor/convert.rb:190)
	at org.jruby.RubyIO.ensureYieldClose(org/jruby/RubyIO.java:1154)
	at org.jruby.RubyIO.open(org/jruby/RubyIO.java:1148)
	at org.jruby.RubyIO$INVOKER$s$0$0$open.call(org/jruby/RubyIO$INVOKER$s$0$0$open.gen)
	at RUBY.convert_file(uri:classloader:/gems/asciidoctor-2.0.17/lib/asciidoctor/convert.rb:190)
	at org.jruby.RubyClass.finvoke(org/jruby/RubyClass.java:782)
	at org.jruby.RubyBasicObject.callMethod(org/jruby/RubyBasicObject.java:370)
	at org.asciidoctor.jruby.internal.JRubyAsciidoctor.convertFile(org/asciidoctor/jruby/internal/JRubyAsciidoctor.java:392)
	at org.asciidoctor.jruby.internal.JRubyAsciidoctor.convertFile(org/asciidoctor/jruby/internal/JRubyAsciidoctor.java:368)
	at org.asciidoctor.maven.AsciidoctorMojo.convertFile(org/asciidoctor/maven/AsciidoctorMojo.java:453)
	at org.asciidoctor.maven.AsciidoctorMojo.processSources(org/asciidoctor/maven/AsciidoctorMojo.java:251)
	at org.asciidoctor.maven.AsciidoctorMojo.processAllSources(org/asciidoctor/maven/AsciidoctorMojo.java:167)
	at org.asciidoctor.maven.AsciidoctorMojo.execute(org/asciidoctor/maven/AsciidoctorMojo.java:157)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(org/apache/maven/plugin/DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(org/apache/maven/lifecycle/internal/MojoExecutor.java:370)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(org/apache/maven/lifecycle/internal/MojoExecutor.java:351)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(org/apache/maven/lifecycle/internal/MojoExecutor.java:215)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(org/apache/maven/lifecycle/internal/MojoExecutor.java:171)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(org/apache/maven/lifecycle/internal/MojoExecutor.java:163)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(org/apache/maven/lifecycle/internal/LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(org/apache/maven/lifecycle/internal/LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(org/apache/maven/lifecycle/internal/builder/singlethreaded/SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(org/apache/maven/lifecycle/internal/LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(org/apache/maven/DefaultMaven.java:298)
	at org.apache.maven.DefaultMaven.doExecute(org/apache/maven/DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(org/apache/maven/DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(org/apache/maven/cli/MavenCli.java:960)
	at org.apache.maven.cli.MavenCli.doMain(org/apache/maven/cli/MavenCli.java:293)
	at org.apache.maven.cli.MavenCli.main(org/apache/maven/cli/MavenCli.java:196)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(jdk/internal/reflect/NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(jdk/internal/reflect/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:568)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(org/codehaus/plexus/classworlds/launcher/Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(org/codehaus/plexus/classworlds/launcher/Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(org/codehaus/plexus/classworlds/launcher/Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(org/codehaus/plexus/classworlds/launcher/Launcher.java:347)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at java.desktop/sun.font.FontManagerFactory$1.run(FontManagerFactory.java:85)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at java.desktop/sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:75)
	at java.desktop/sun.font.SunFontManager.getInstance(SunFontManager.java:248)
	at java.desktop/sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:266)
	at java.desktop/sun.java2d.SunGraphics2D.getFontMetrics(SunGraphics2D.java:863)
	at org.stathissideris.ascii2image.graphics.FontMeasurer.getAscent(FontMeasurer.java:80)
	at org.stathissideris.ascii2image.graphics.FontMeasurer$2.test(FontMeasurer.java:110)
	at org.stathissideris.ascii2image.graphics.FontMeasurer.deriveFont(FontMeasurer.java:124)
	at org.stathissideris.ascii2image.graphics.FontMeasurer.getFontFor(FontMeasurer.java:115)
	at org.stathissideris.ascii2image.graphics.Diagram.<init>(Diagram.java:493)
	at org.asciidoctor.diagram.ditaa.Ditaa.convertToImage(Ditaa.java:104)
	at org.asciidoctor.diagram.ditaa.Ditaa.doConvert(Ditaa.java:73)
	at org.asciidoctor.diagram.ditaa.Ditaa.generate(Ditaa.java:62)
	at org.asciidoctor.diagram.CommandProcessor.processRequest(CommandProcessor.java:40)
	at org.asciidoctor.diagram.CommandProcessor.processRequest(CommandProcessor.java:19)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:457)
	at org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:318)
	at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:42)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:372)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:175)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:316)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
	at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:86)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:201)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:188)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:218)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:372)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:175)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:316)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:128)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:115)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:329)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:87)
	at org.jruby.ir.instructions.CallBase.interpret(CallBase.java:549)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:361)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:128)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:115)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:329)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:87)
	at org.jruby.ir.instructions.CallBase.interpret(CallBase.java:549)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:361)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:128)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:115)
	at org.jruby.RubyMethod.call(RubyMethod.java:131)
	at org.jruby.RubyMethod$INVOKER$i$call.call(RubyMethod$INVOKER$i$call.gen)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:329)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:87)
	at org.jruby.ir.instructions.CallBase.interpret(CallBase.java:549)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:361)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:128)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:115)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:329)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:87)
	at org.jruby.ir.instructions.CallBase.interpret(CallBase.java:549)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:361)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:128)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:115)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:329)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:87)
	at org.jruby.ir.instructions.CallBase.interpret(CallBase.java:549)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:361)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:128)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:115)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:85)
	at org.jruby.ir.instructions.CallBase.interpret(CallBase.java:549)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:361)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:128)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:115)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:85)
	at org.jruby.ir.instructions.CallBase.interpret(CallBase.java:549)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:361)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:128)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:115)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:329)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:87)
	at org.jruby.ir.instructions.CallBase.interpret(CallBase.java:549)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:361)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:128)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:115)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:329)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:87)
	at org.jruby.ir.instructions.CallBase.interpret(CallBase.java:549)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:361)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:128)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:115)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:329)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:87)
	at org.jruby.ir.instructions.CallBase.interpret(CallBase.java:549)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:361)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
	at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:80)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:164)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:151)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:210)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:351)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:144)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:345)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
	at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:92)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:238)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:225)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:226)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:393)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:206)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:325)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
	at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:92)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:238)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:225)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:226)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:393)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:206)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:325)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
	at org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:116)
	at org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:136)
	at org.jruby.runtime.IRBlockBody.doYield(IRBlockBody.java:170)
	at org.jruby.runtime.BlockBody.yield(BlockBody.java:108)
	at org.jruby.runtime.Block.yield(Block.java:188)
	at org.jruby.RubyIO.ensureYieldClose(RubyIO.java:1154)
	at org.jruby.RubyIO.open(RubyIO.java:1148)
	at org.jruby.RubyIO$INVOKER$s$0$0$open.call(RubyIO$INVOKER$s$0$0$open.gen)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:329)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:87)
	at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:94)
	at org.jruby.ir.instructions.CallBase.interpret(CallBase.java:546)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:361)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:128)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:115)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:192)
	at org.jruby.RubyClass.finvoke(RubyClass.java:782)
	at org.jruby.runtime.Helpers.invoke(Helpers.java:661)
	at org.jruby.RubyBasicObject.callMethod(RubyBasicObject.java:370)
	at org.asciidoctor.jruby.internal.JRubyAsciidoctor.convertFile(JRubyAsciidoctor.java:392)
	at org.asciidoctor.jruby.internal.JRubyAsciidoctor.convertFile(JRubyAsciidoctor.java:368)
	at org.asciidoctor.maven.AsciidoctorMojo.convertFile(AsciidoctorMojo.java:453)
	at org.asciidoctor.maven.AsciidoctorMojo.processSources(AsciidoctorMojo.java:251)
	at org.asciidoctor.maven.AsciidoctorMojo.processAllSources(AsciidoctorMojo.java:167)
	at org.asciidoctor.maven.AsciidoctorMojo.execute(AsciidoctorMojo.java:157)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:370)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:351)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:215)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:171)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:163)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:298)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:960)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Caused by: java.lang.NullPointerException: Cannot load from short array because "sun.awt.FontConfiguration.head" is null
	at java.desktop/sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1264)
	at java.desktop/sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:224)
	at java.desktop/sun.awt.FontConfiguration.init(FontConfiguration.java:106)
	at java.desktop/sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:706)
	at java.desktop/sun.font.SunFontManager$2.run(SunFontManager.java:358)
	at java.desktop/sun.font.SunFontManager$2.run(SunFontManager.java:315)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at java.desktop/sun.font.SunFontManager.<init>(SunFontManager.java:315)
	at java.desktop/sun.awt.FcFontManager.<init>(FcFontManager.java:35)
	at java.desktop/sun.awt.X11FontManager.<init>(X11FontManager.java:56)
	... 184 more
```

**Comment by meistermeier** [comment]
Let's investigate this next week together.
I have no idea why this suddenly fails. AFAIK we changed nothing but text in the documentation. No dependencies or configuration.

**Comment by mp911de** [comment]
I anticipate that we need to make changes to our build environment and not so much a change in this project.
