### ISSUE TITLE
 Error creating bean with name 'getSessionFactory' under Windows (sdn4)

### ISSUE THREAD

**Issue by maku** [spring-projects/spring-data-neo4j#270]
See also issue of example application (sdn4-university) SessionFactory - https://github.com/neo4j-examples/sdn4-university/issues/1

08:10:11.908 [main] WARN  o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext - Exception encountered during context initialization - cancelling refresh attempt
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'getSessionFactory' defined in school.Application: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Fail
ed to instantiate [org.neo4j.ogm.session.SessionFactory]: Factory method 'getSessionFactory' threw exception; nested exception is j
ava.lang.IllegalArgumentException: character to be escaped is missing
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599
) ~[spring-beans-4.1.4.RELEASE.jar:4.1.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutow
ireCapableBeanFactory.java:1111) ~[spring-beans-4.1.4.RELEASE.jar:4.1.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableB
eanFactory.java:1006) ~[spring-beans-4.1.4.RELEASE.jar:4.1.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFac
tory.java:504) ~[spring-beans-4.1.4.RELEASE.jar:4.1.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFacto
ry.java:476) ~[spring-beans-4.1.4.RELEASE.jar:4.1.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303) ~[spring-beans-4
.1.4.RELEASE.jar:4.1.4.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:23
0) ~[spring-beans-4.1.4.RELEASE.jar:4.1.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299) ~[spring-beans-4.1
.4.RELEASE.jar:4.1.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194) ~[spring-beans-4.1.4
.RELEASE.jar:4.1.4.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory
.java:762) ~[spring-beans-4.1.4.RELEASE.jar:4.1.4.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContex
t.java:757) ~[spring-context-4.1.4.RELEASE.jar:4.1.4.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480) ~[spring-con
text-4.1.4.RELEASE.jar:4.1.4.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:109)
[spring-boot-1.1.10.RELEASE.jar:1.1.10.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:691) [spring-boot-1.1.10.RELEASE.jar:1.1.10.RE
LEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:320) [spring-boot-1.1.10.RELEASE.jar:1.1.10.RELEAS
E]
        at school.Application.main(Application.java:92) [classes/:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.neo4j.ogm.session.SessionFactory]: Fact
ory method 'getSessionFactory' threw exception; nested exception is java.lang.IllegalArgumentException: character to be escaped is
missing
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
~[spring-beans-4.1.4.RELEASE.jar:4.1.4.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588
) ~[spring-beans-4.1.4.RELEASE.jar:4.1.4.RELEASE]
        ... 15 common frames omitted
Caused by: java.lang.IllegalArgumentException: character to be escaped is missing
        at java.util.regex.Matcher.appendReplacement(Matcher.java:809) ~[na:1.8.0_20]
        at java.util.regex.Matcher.replaceAll(Matcher.java:955) ~[na:1.8.0_20]
        at java.lang.String.replaceAll(String.java:2210) ~[na:1.8.0_20]
        at org.neo4j.ogm.metadata.info.DomainInfo.load(DomainInfo.java:220) ~[neo4j-ogm-1.0.0.M1.jar:na]
        at org.neo4j.ogm.metadata.info.DomainInfo.<init>(DomainInfo.java:48) ~[neo4j-ogm-1.0.0.M1.jar:na]
        at org.neo4j.ogm.metadata.MetaData.<init>(MetaData.java:38) ~[neo4j-ogm-1.0.0.M1.jar:na]
        at org.neo4j.ogm.session.SessionFactory.<init>(SessionFactory.java:30) ~[neo4j-ogm-1.0.0.M1.jar:na]
        at school.Application.getSessionFactory(Application.java:56) [classes/:na]
        at school.Application$$EnhancerBySpringCGLIB$$24779915.CGLIB$getSessionFactory$0(<generated>) ~[spring-core-4.1.4.RELEASE.j
ar:na]
        at school.Application$$EnhancerBySpringCGLIB$$24779915$$FastClassBySpringCGLIB$$37781629.invoke(<generated>) ~[spring-core-

**Comment by vince-bickers** [comment]
This bug is currently being addressed. You can track its status here:

https://jira.spring.io/browse/DATAGRAPH-606
