### ISSUE TITLE
For derived queries support OffsetDateTime and LocalTime

### ISSUE THREAD

**Issue by Skym0sh0** [spring-projects/spring-data-neo4j#2706]
I have a data class that contains some timestamps with the type `java.time.OffsetDateTime`.
Now I want to write (or better to say: let generate) a derived query that does filtering with `isBefore` and `isAfter` on such a OffsetDateTime field.

When those queries are generated I receive an error that isBefore/isAfter can not be used together with OffsetDateTime.

```java
Caused by: java.lang.IllegalArgumentException: Can not derive query for 'public abstract java.util.List my.package.MyExampleRepository.findByLastModifiedDateIsAfter(java.time.OffsetDateTime)': The keywords [IsAfter, After] work only with properties with one of the following types: [class java.time.Instant, class java.time.LocalDate, class java.time.LocalDateTime, class java.time.OffsetTime, class java.time.ZonedDateTime].
	at org.springframework.util.Assert.isTrue(Assert.java:139)
	at org.springframework.data.neo4j.repository.query.PartValidator.validateTemporalProperty(PartValidator.java:116)
	at org.springframework.data.neo4j.repository.query.PartValidator.validatePart(PartValidator.java:82)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.springframework.data.neo4j.repository.query.PartTreeNeo4jQuery.<init>(PartTreeNeo4jQuery.java:60)
	at org.springframework.data.neo4j.repository.query.PartTreeNeo4jQuery.create(PartTreeNeo4jQuery.java:50)
	at org.springframework.data.neo4j.repository.query.Neo4jQueryLookupStrategy.resolveQuery(Neo4jQueryLookupStrategy.java:70)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.lookupQuery(QueryExecutorMethodInterceptor.java:103)
```

When looking at the error message I am asking myself:
Why is OffsetDateTime and LocalTime not supported?
Why is OffsetTime (which I never heard of yet) supported?
What can I do as a workaround?

**Comment by michael-simons** [comment]
This is most likely an oversight or left over from older versions of the underlying driver not converting these types proper. Will be fixed shortly.
