### ISSUE TITLE
Crashes when using SpringCypherRestGraphDatabase, cypher query returning @QueryResult containing a Collection of relationships

### ISSUE THREAD

**Issue by RanGold** [spring-projects/spring-data-neo4j#278]
Crashes when using SpringCypherRestGraphDatabase, cypher query returning @QueryResult containing a Collection of @RelationshipEntity.
This specifically happens when the collection returned from the query contains only 1 element.
The exception received is:
```
java.lang.RuntimeException: Cannot extract single value from Iterable with more than one elements.
	at org.springframework.data.neo4j.conversion.DefaultConverter.extractSingle(DefaultConverter.java:61)
	at org.springframework.data.neo4j.conversion.DefaultConverter.extractValue(DefaultConverter.java:52)
	at org.springframework.data.neo4j.conversion.DefaultConverter.convert(DefaultConverter.java:41)
	at org.springframework.data.neo4j.support.conversion.EntityResultConverter.convert(EntityResultConverter.java:165)
	at org.springframework.data.neo4j.conversion.QueryResultBuilder$1.underlyingObjectToObject(QueryResultBuilder.java:86)
	at org.neo4j.helpers.collection.IterableWrapper$MyIteratorWrapper.underlyingObjectToObject(IterableWrapper.java:57)
	at org.neo4j.helpers.collection.IteratorWrapper.next(IteratorWrapper.java:47)
	at org.neo4j.helpers.collection.IteratorUtil.addToCollection(IteratorUtil.java:382)
	at org.neo4j.helpers.collection.IteratorUtil.addToCollection(IteratorUtil.java:461)
	at org.springframework.data.neo4j.conversion.ContainerConverter.toContainer(ContainerConverter.java:42)
	at org.springframework.data.neo4j.conversion.QueryResultBuilder.as(QueryResultBuilder.java:96)
	at org.springframework.data.neo4j.support.conversion.ResultColumnValueExtractor.extractFromAccessibleObject(ResultColumnValueExtractor.java:82)
	at org.springframework.data.neo4j.support.conversion.ResultColumnValueExtractor.extractFromMethod(ResultColumnValueExtractor.java:56)
	at org.springframework.data.neo4j.support.conversion.QueryResultProxy.invoke(QueryResultProxy.java:54)
	at com.sun.proxy.$Proxy206.getMembers(Unknown Source)
```

**Comment by jexp** [comment]
Provide your code: both repository, domain entities, queries, etc. otherwise we can't help you.

**Comment by mangrish** [comment]
Closed. Issue out of date.
