### ISSUE TITLE
Exception while running with Neo4j 3.5.3

### ISSUE THREAD

**Issue by ranjith1235** [spring-projects/spring-data-neo4j#2847]
I am using `spring-boot-starter-data-neo4j` with the following plugins:
```
id 'org.springframework.boot' version '3.2.0'
id 'io.spring.dependency-management' version '1.1.4'
```

 I am using Neo4j 3.5.3 docker container for running the application. I also tried the sample code mentioned here [https://github.com/spring-guides/gs-accessing-data-neo4j](url) and still got the same issue.

Below is the exception which I am seeing while running the app.

```
2023-12-19T09:21:19.645+05:30  INFO 88294 --- [           main] .s.b.a.l.ConditionEvaluationReportLogger : 

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2023-12-19T09:21:19.663+05:30 ERROR 88294 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:789) ~[spring-boot-3.2.0.jar:3.2.0]
	at org.springframework.boot.SpringApplication.lambda$callRunners$3(SpringApplication.java:770) ~[spring-boot-3.2.0.jar:3.2.0]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[na:na]
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[na:na]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:765) ~[spring-boot-3.2.0.jar:3.2.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:330) ~[spring-boot-3.2.0.jar:3.2.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1342) ~[spring-boot-3.2.0.jar:3.2.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1331) ~[spring-boot-3.2.0.jar:3.2.0]
	at com.example.accessingdataneo4j.AccessingDataNeo4jApplication.main(AccessingDataNeo4jApplication.java:23) ~[main/:na]
Caused by: org.springframework.dao.NonTransientDataAccessResourceException: Expected 
RegularPlannerQuery(QueryGraph {Nodes: ['  rootNodeIds@7'], Predicates: ['id(`  rootNodeIds@7`) IN $rootNodeIds', '`  rootNodeIds@7`:Person']},InterestingOrder(List(),List()),AggregatingQueryProjection(Map(),Map(n -> FunctionInvocation(Namespace(List()),FunctionName(collect),false,Vector(Variable(  rootNodeIds@7)))),QueryShuffle(List(),None,None),Selections(Set())),Some(RegularPlannerQuery(QueryGraph {Arguments: ['n'], Optional Matches: : ['QueryGraph {Rels: ['(  UNNAMED114)--[relationshipIds]--(  UNNAMED135)'], Predicates: ['id(relationshipIds) IN $relationshipIds']}']},InterestingOrder(List(),List()),AggregatingQueryProjection(Map(n -> Variable(n)),Map(__sr__ -> FunctionInvocation(Namespace(List()),FunctionName(collect),true,Vector(Variable(relationshipIds)))),QueryShuffle(List(),None,None),Selections(Set())),Some(RegularPlannerQuery(QueryGraph {Arguments: ['__sr__', 'n'], Optional Matches: : ['QueryGraph {Nodes: ['relatedNodeIds'], Predicates: ['id(relatedNodeIds) IN $relatedNodeIds']}']},InterestingOrder(List(),List()),AggregatingQueryProjection(Map(n -> Variable(n), __sr__ -> Variable(__sr__)),Map(__srn__ -> FunctionInvocation(Namespace(List()),FunctionName(collect),true,Vector(Variable(relatedNodeIds)))),QueryShuffle(List(),None,None),Selections(Set())),Some(RegularPlannerQuery(QueryGraph {Arguments: ['__sr__', '__srn__', 'n']},InterestingOrder(List(),List()),UnwindProjection(  rootNodeIds@393,Variable(n)),Some(RegularPlannerQuery(QueryGraph {Arguments: ['  rootNodeIds@393', '__sr__', '__srn__', 'n']},InterestingOrder(List(),List()),RegularQueryProjection(Map(person -> Variable(  rootNodeIds@393), __sr__ -> Variable(__sr__), __srn__ -> Variable(__srn__)),QueryShuffle(List(),None,None),Selections(Set())),Some(RegularPlannerQuery(QueryGraph {Arguments: ['__sr__', '__srn__', 'person']},InterestingOrder(List(),List()),RegularQueryProjection(Map(__sn__ -> Variable(person), __sr__ -> Variable(__sr__), __srn__ -> Variable(__srn__)),QueryShuffle(List(),None,None),Selections(Set())),None))))))))))) 


Instead, got: 
RegularPlannerQuery(QueryGraph {Nodes: ['  rootNodeIds@7'], Predicates: ['`  rootNodeIds@7`:Person', 'id(`  rootNodeIds@7`) IN $rootNodeIds']},InterestingOrder(List(),List()),AggregatingQueryProjection(Map(),Map(n -> FunctionInvocation(Namespace(List()),FunctionName(collect),false,Vector(Variable(  rootNodeIds@7)))),QueryShuffle(List(),None,None),Selections(Set())),Some(RegularPlannerQuery(QueryGraph {Arguments: ['n'], Optional Matches: : ['QueryGraph {}']},InterestingOrder(List(),List()),AggregatingQueryProjection(Map(n -> Variable(n)),Map(__sr__ -> FunctionInvocation(Namespace(List()),FunctionName(collect),true,Vector(Variable(relationshipIds)))),QueryShuffle(List(),None,None),Selections(Set())),Some(RegularPlannerQuery(QueryGraph {Arguments: ['__sr__', 'n'], Optional Matches: : ['QueryGraph {Nodes: ['relatedNodeIds'], Predicates: ['id(relatedNodeIds) IN $relatedNodeIds']}']},InterestingOrder(List(),List()),AggregatingQueryProjection(Map(n -> Variable(n), __sr__ -> Variable(__sr__)),Map(__srn__ -> FunctionInvocation(Namespace(List()),FunctionName(collect),true,Vector(Variable(relatedNodeIds)))),QueryShuffle(List(),None,None),Selections(Set())),Some(RegularPlannerQuery(QueryGraph {Arguments: ['__sr__', '__srn__', 'n']},InterestingOrder(List(),List()),UnwindProjection(  rootNodeIds@393,Variable(n)),Some(RegularPlannerQuery(QueryGraph {Arguments: ['  rootNodeIds@393', '__sr__', '__srn__', 'n']},InterestingOrder(List(),List()),RegularQueryProjection(Map(person -> Variable(  rootNodeIds@393), __sr__ -> Variable(__sr__), __srn__ -> Variable(__srn__)),QueryShuffle(List(),None,None),Selections(Set())),Some(RegularPlannerQuery(QueryGraph {Arguments: ['__sr__', '__srn__', 'person']},InterestingOrder(List(),List()),RegularQueryProjection(Map(__sn__ -> Variable(person), __sr__ -> Variable(__sr__), __srn__ -> Variable(__srn__)),QueryShuffle(List(),None,None),Selections(Set())),None)))))))))))
Plan: Projection(Map(__sn__ -> Variable(person))) {
  LHS -> Apply() {
    LHS -> Projection(Map(person -> Variable(  rootNodeIds@393))) {
      LHS -> Apply() {
        LHS -> UnwindCollection(  rootNodeIds@393, Variable(n)) {
          LHS -> Apply() {
            LHS -> Aggregation(Map(n -> Variable(n), __sr__ -> Variable(__sr__)), Map(__srn__ -> FunctionInvocation(Namespace(List()),FunctionName(collect),true,Vector(Variable(relatedNodeIds))))) {
              LHS -> Apply() {
                LHS -> Aggregation(Map(n -> Variable(n)), Map(__sr__ -> FunctionInvocation(Namespace(List()),FunctionName(collect),true,Vector(Variable(relationshipIds))))) {
                  LHS -> Apply() {
                    LHS -> Aggregation(Map(), Map(n -> FunctionInvocation(Namespace(List()),FunctionName(collect),false,Vector(Variable(  rootNodeIds@7))))) {
                      LHS -> Selection(Ands(Set(In(FunctionInvocation(Namespace(List()),FunctionName(id),false,Vector(Variable(  rootNodeIds@7))),Parameter(rootNodeIds,Any))))) {
                        LHS -> NodeByLabelScan(  rootNodeIds@7, LabelName(Person), Set()) {}
                      }
                    }
                    RHS -> Apply() {
                      LHS -> Argument(Set(n)) {}
                      RHS -> Optional(Set(n)) {
                        LHS -> Argument(Set()) {}
                      }
                    }
                  }
                }
                RHS -> Apply() {
                  LHS -> Argument(Set(n, __sr__)) {}
                  RHS -> Optional(Set(n, __sr__)) {
                    LHS -> Selection(Ands(Set(In(FunctionInvocation(Namespace(List()),FunctionName(id),false,Vector(Variable(relatedNodeIds))),Parameter(relatedNodeIds,Any))))) {
                      LHS -> AllNodesScan(relatedNodeIds, Set()) {}
                    }
                  }
                }
              }
            }
            RHS -> Argument(Set(n, __sr__, __srn__)) {}
          }
        }
        RHS -> Argument(Set(n, __sr__, __srn__,   rootNodeIds@393)) {}
      }
    }
    RHS -> Argument(Set(person, __sr__, __srn__)) {}
  }
}; Error code Neo.DatabaseError.Statement.ExecutionFailed

```

**Comment by meistermeier** [comment]
Sorry, I cannot interpret the problem the query planner is seeing.
Current Spring Data Neo4j versions do not officially support Neo4j 3.5 anymore but have a test baseline at 4.4 (current LTS).
Also 3.5 is EOL since May 27, 2022. Is there any reason why you have chosen to use 3.5?

Having said this, we should remove the reference to testing with 3.5 from the documentation.

**Comment by ranjith1235** [comment]
I am very new to neo4j and their official site had example for 3.5 version. I tried with the latest version of neo4j and it works fine. Thanks for the tip.

**Comment by meistermeier** [comment]
Could you please point me where 3.5 is mentioned (beyond some testing/migration sections in the Spring Data Neo4j docs)?

**Comment by ranjith1235** [comment]
Not on Spring Data Neo4j docs. Its on Neo4j docs [https://neo4j.com/developer/docker-run-neo4j/](url)

**Comment by meistermeier** [comment]
Ah, ok. It might not be sooo visible but there is a warning note, saying that this document is not maintained.
![image](https://github.com/spring-projects/spring-data-neo4j/assets/435872/02124fd8-80b6-4242-b5c6-2fd18d726df0)

The link directs you to https://neo4j.com/docs/operations-manual/current/docker/ with more current information.
