### ISSUE TITLE
Passing Pageable.unpaged() to findAll() throws java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by ilgrosso** [spring-projects/spring-data-neo4j#2878]
The code at https://github.com/spring-projects/spring-data-neo4j/blob/main/src/main/java/org/springframework/data/neo4j/repository/query/QueryFragmentsAndParameters.java#L370-L373 is not behaving well when an instance of `org.springframework.data.domain.org.springframework.data.domain.Unpaged` - obtained by `Pageable.unpaged()` is passed as argument to `findAll()`

Full stacktrace:

```
java.lang.UnsupportedOperationException: null
        at org.springframework.data.domain.Unpaged.getOffset(Unpaged.java:75) ~[spring-data-commons-3.2.3.jar:3.2.3]
        at org.springframework.data.neo4j.repository.query.QueryFragmentsAndParameters.adaptPageable(QueryFragmentsAndParameters.java:371) ~[spring-data-neo4j-7.2.3.jar:7.2.3]
        at org.springframework.data.neo4j.repository.query.QueryFragmentsAndParameters.getQueryFragmentsAndParameters(QueryFragmentsAndParameters.java:345) ~[spring-data-neo4j-7.2.3.jar:7.2.3]
        at org.springframework.data.neo4j.repository.query.QueryFragmentsAndParameters.forPageableAndSort(QueryFragmentsAndParameters.java:181) ~[spring-data-neo4j-7.2.3.jar:7.2.3]
        at org.springframework.data.neo4j.repository.support.SimpleNeo4jRepository.findAll(SimpleNeo4jRepository.java:97) ~[spring-data-neo4j-7.2.3.jar:4.0.0-SNAPSHOT]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:351) ~[spring-aop-6.1.4.jar:6.1.4]
        at org.springframework.data.repository.core.support.RepositoryMethodInvoker$RepositoryFragmentMethodInvoker.lambda$new$0(RepositoryMethodInvoker.java:277) ~[spring-data-commons-3.2.3.jar:3.2.3]
        at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:170) ~[spring-data-commons-3.2.3.jar:3.2.3]
        at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:158) ~[spring-data-commons-3.2.3.jar:3.2.3]
        at org.springframework.data.repository.core.support.RepositoryComposition$RepositoryFragments.invoke(RepositoryComposition.java:516) ~[spring-data-commons-3.2.3.jar:3.2.3]
        at org.springframework.data.repository.core.support.RepositoryComposition.invoke(RepositoryComposition.java:285) ~[spring-data-commons-3.2.3.jar:3.2.3]
        at org.springframework.data.repository.core.support.RepositoryFactorySupport$ImplementationMethodExecutionInterceptor.invoke(RepositoryFactorySupport.java:628) ~[spring-data-commons-3.2.3.jar:3.2.3]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.1.4.jar:6.1.4]
        at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:168) ~[spring-data-commons-3.2.3.jar:3.2.3]
        at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:143) ~[spring-data-commons-3.2.3.jar:3.2.3]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.1.4.jar:6.1.4]
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) ~[spring-aop-6.1.4.jar:6.1.4]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.1.4.jar:6.1.4]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:220) ~[spring-aop-6.1.4.jar:6.1.4]
        at jdk.proxy4/jdk.proxy4.$Proxy386.findAll(Unknown Source) ~[?:?]
```

**Comment by michael-simons** [comment]
… and back ported into several older branches.

Thanks again, Francesco.

**Comment by ilgrosso** [comment]
Great, thanks for the quick review :+1:
