### ISSUE TITLE
Relationship should support UUID id like node

### ISSUE THREAD

**Issue by abccbaandy** [spring-projects/spring-data-neo4j#2982]
I want both node and relationship have the same id format.

In node
````java
    @Id
    @GeneratedValue
    private UUID id;
````
This work well

But in relationship
````java
    @RelationshipId
    private UUID id;
````
It failed to start
````java
Caused by: java.lang.IllegalStateException: The class `XXX.MyRelationship` for the properties of a relationship is missing a property for the generated, internal ID (`@Id @GeneratedValue Long id` or `@Id @GeneratedValue String id`) which is needed for safely updating properties
	at org.springframework.util.Assert.state(Assert.java:101) ~[spring-core-6.2.1.jar:6.2.1]
	at org.springframework.data.neo4j.core.mapping.DefaultNeo4jPersistentEntity.verifyAssociationsWithProperties(DefaultNeo4jPersistentEntity.java:272) ~[spring-data-neo4j-7.4.1.jar:7.4.1]
	at org.springframework.data.neo4j.core.mapping.DefaultNeo4jPersistentEntity.verify(DefaultNeo4jPersistentEntity.java:205) ~[spring-data-neo4j-7.4.1.jar:7.4.1]
````

I also try with 
````java
    @Id
    @GeneratedValue(generatorClass = UUIDStringGenerator.class)
    private String id;
````
But no luck

**Comment by michael-simons** [comment]
We don't exposes relationships as entities, the `@RelationshipId` is required internally only, to be used to identify the objects. It must either be a `long`, `Long` OR a `String` attribute. The latter is the case when using Neo4j 5 with element ids. See https://docs.spring.io/spring-data/neo4j/reference/object-mapping/metadata-based-mapping.html#mapping.annotations.relationship.properties

**Comment by michael-simons** [comment]
Hm, you can assign any `randomUUID()` to a property… Either from within SDN through a callback: https://github.com/spring-projects/spring-data-neo4j/blob/main/src/main/java/org/springframework/data/neo4j/core/mapping/callback/BeforeBindCallback.java or inside the database. What that work for you?

**Comment by michael-simons** [comment]
You could write an APOC trigger or similar. But in all fairness, that would be my least favourable solution for my own stuff I guess.

**Comment by michael-simons** [comment]
* The audit feature applies to all operations going through the templates and repositories. Sure, if you go around it by plain cypher or driver or combinations thereof, it's bypassed
* However, you are right, things like these are for sure a trigger based approach
* Trigger on the other hand usually don't play nice with any kind of object mapper, as it would require an active refresh of what has been changed outside the mapper

The latter is the tradeoff I would avoid here mostly.

**Comment by michael-simons** [comment]
> I am guess it's like JPA world : When save an entity, field with MySql default value missing in the return object?

Yes.
