### ISSUE TITLE
DateLong annotated property cannot be prepopulated with 0L in cypher statements

### ISSUE THREAD

**Issue by viswanath7** [spring-projects/spring-data-neo4j#311]
In my Person node annotated with @NodeEntity, I've 2 Long properties namely
lastPortalLoginTime and lastSocialLoginTime
annotated with @DateLong. These fields contain date-time in ms stored as long.

The problem is, cypher's merge won't allow to me to specify 0L but only ones like below are allowed
In the cypher query that pre-populates data looks something like
MERGE (p:Person {lastPortalLoginTime:1388580726000, lastSocialLoginTime:0});
Which isn't accepted by DateLong converter of SDN as it ends up in a class cast exception.

Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
at org.neo4j.ogm.typeconversion.DateLongConverter.toEntityAttribute(DateLongConverter.java:22)
at org.neo4j.ogm.entityaccess.FieldWriter.write(FieldWriter.java:64)
at org.neo4j.ogm.mapper.GraphEntityMapper.writeProperty(GraphEntityMapper.java:164)
at org.neo4j.ogm.mapper.GraphEntityMapper.setProperties(GraphEntityMapper.java:129)
at org.neo4j.ogm.mapper.GraphEntityMapper.mapNodes(GraphEntityMapper.java:110)
at org.neo4j.ogm.mapper.GraphEntityMapper.mapEntities(GraphEntityMapper.java:94)
... 74 more

The problem here is that of compatibility between SDN v4 and Neo4j 2.2.5.

**Comment by jexp** [comment]
Which version are you using ? 4.0.0.RELEASE?

Please raise the issue at the JIRA issue tracker https://jira.spring.io/browse/DATAGRAPH

Thanks a lot

**Comment by viswanath7** [comment]
Yes. I'm using SDN 4.0.0.RELEASE. 
I'll raise an issue there. Thanks!
