### ISSUE TITLE
[4.1] "Projection type must be an interface" error when returned relationship result is null

### ISSUE THREAD

**Issue by justinjohn83** [spring-projects/spring-data-neo4j#327]
In latest snapshot build for 4.1 I am getting "java.lang.IllegalArgumentException: Projection type must be an interface!".  I wrote a unit test and this seems to be occurring when invoking a custom query on a GraphRepository interface that returns a relationship in cases where relationship doesn't exist.  

for example a query such as the following:

	@Query("match (a)-[r]->(b) where id(a)={0} and id(b)={1} return r")
	public RelationshipDomainType getRelationship(Long sourceId, Long targetId)

Below is full relevant stack trace:

java.lang.IllegalArgumentException: Projection type must be an interface!
	at org.springframework.util.Assert.isTrue(Assert.java:68)
	at org.springframework.data.projection.ProxyProjectionFactory.createProjection(ProxyProjectionFactory.java:80)
	at org.springframework.data.projection.SpelAwareProxyProjectionFactory.createProjection(SpelAwareProxyProjectionFactory.java:41)
	at org.springframework.data.repository.query.ResultProcessor$ProjectingConverter.convert(ResultProcessor.java:221)
	at org.springframework.data.repository.query.ResultProcessor$ChainingConverter$1.convert(ResultProcessor.java:174)
	at org.springframework.data.repository.query.ResultProcessor$ChainingConverter.convert(ResultProcessor.java:185)
	at org.springframework.data.repository.query.ResultProcessor.processResult(ResultProcessor.java:148)
	at org.springframework.data.repository.query.ResultProcessor.processResult(ResultProcessor.java:110)
	at org.springframework.data.neo4j.repository.query.GraphRepositoryQuery.execute(GraphRepositoryQuery.java:54)

**Comment by ziaulhaquefarooqui** [comment]
I am also facing the same issue while rendering the query below
"MATCH (channel:Channel {deleted:false}) --> (template:Template) where id(channel)={0} return template" in case when template is null or no result.

**Comment by luanne** [comment]
Which version are you using? This was fixed in the Hopper release (4.1.1) https://jira.spring.io/browse/DATACMNS-828

**Comment by ziaulhaquefarooqui** [comment]
I was using the 4.1.0, Thanks for the updates.

**Comment by luanne** [comment]
@justinjohn83 , @ziaulhaquefarooqui please confirm if the release upgrade fixes the problem, thanks

**Comment by luanne** [comment]
Please reopen if the issue surfaces again.
