### ISSUE TITLE
Transaction issue after server inactivity (4.2.0.BUILD-SNAPSHOT)

### ISSUE THREAD

**Issue by tavolate** [spring-projects/spring-data-neo4j#373]
Neo4j server version: 3.0.7
Spring data neo4j: 4.2.0.M1
Neo4j ogm bolt driver: 2.0.5

Our web application is deployed on AWS Elastic beanstalk. It works well, but after a period of inactivity, the first request fails with this error 

`java.lang.NullPointerException
	at org.springframework.data.neo4j.transaction.Neo4jTransactionManager.doRollback(Neo4jTransactionManager.java:265) ~[spring-data-neo4j-4.2.0.M1.jar:?]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processRollback(AbstractPlatformTransactionManager.java:853) ~[spring-tx-4.3.0.RELEASE.jar:4.3.0.RELEASE]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.rollback(AbstractPlatformTransactionManager.java:830) ~[spring-tx-4.3.0.RELEASE.jar:4.3.0.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.completeTransactionAfterThrowing(TransactionAspectSupport.java:503) ~[spring-tx-4.3.0.RELEASE.jar:4.3.0.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:285) ~[spring-tx-4.3.0.RELEASE.jar:4.3.0.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) ~[spring-tx-4.3.0.RELEASE.jar:4.3.0.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.0.RELEASE.jar:4.3.0.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655) ~[spring-aop-4.3.0.RELEASE.jar:4.3.0.RELEASE]
`

Issuing the same request again succeeds.

**Comment by mangrish** [comment]
@tavolate Can you try with SDN 4.2.0.BUILD-SNAPSHOT and OGM 2.1.0-SNAPSHOT. These are about to go GA soon so they are more developed and stable than M1 and 2.0.5

**Comment by tavolate** [comment]
Neo4j server version: 3.0.7
Spring data neo4j: 4.2.0.BUILD-SNAPSHOT
Neo4j ogm bolt driver: 2.1.0-SNAPSHOT

@mangrish I updated the version but we have the same error.

`java.lang.NullPointerException
	at org.springframework.data.neo4j.transaction.Neo4jTransactionManager.doRollback(Neo4jTransactionManager.java:275) ~[spring-data-neo4j-4.2.0.BUILD-20161110.100915-135.jar:?]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processRollback(AbstractPlatformTransactionManager.java:853) ~[spring-tx-4.3.0.RELEASE.jar:4.3.0.RELEASE]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.rollback(AbstractPlatformTransactionManager.java:830) ~[spring-tx-4.3.0.RELEASE.jar:4.3.0.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.completeTransactionAfterThrowing(TransactionAspectSupport.java:503) ~[spring-tx-4.3.0.RELEASE.jar:4.3.0.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:285) ~[spring-tx-4.3.0.RELEASE.jar:4.3.0.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) ~[spring-tx-4.3.0.RELEASE.jar:4.3.0.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.0.RELEASE.jar:4.3.0.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655) ~[spring-aop-4.3.0.RELEASE.jar:4.3.0.RELEASE]`

**Comment by tavolate** [comment]
With neo4j-java-driver 1.1.0-M06 we have this error 

`org.springframework.data.neo4j.exception.UncategorizedNeo4jException: Error executing Cypher; Code: N/A; Description: SSL Connection terminated while receiving data. This can happen due to network instabilities, or due to restarts of the database.; nested exception is org.neo4j.ogm.exception.CypherException: Error e
xecuting Cypher; Code: N/A; Description: SSL Connection terminated while receiving data. This can happen due to network instabilities, or due to restarts of the database.
`

**Comment by mangrish** [comment]
@tavolate This error looks extremely unusual. Is AWS hibernating your Neo4j instance? See: https://github.com/neo4j/neo4j-java-driver/issues/267. This looks like an issue with either AWS or the driver. I suggest you create a ticket on them and if you can provide some code that they can run on AWS to replicate (including the steps).

**Comment by tavolate** [comment]
Thank you for your help. I investigate with the provider of the database service (graphene db) and I discovered that the free plan (sandbox) goes to sleep after a while. I think our issue is due to this behavior.

**Comment by mangrish** [comment]
You might want to try the HTTP driver for your situation since it's stateless. The bolt driver might hold some state with it's protocol.

**Comment by tavolate** [comment]
is the bolt protocol better than http? (I think so)

**Comment by mangrish** [comment]
performance wise? yes. But it's also fairly new (as of Neo4j 3.x). I would recommend adding your case here as a ticket for them so it can be prioritised. In my opinion the driver should work still. Even after a reboot of the database.

**Comment by tavolate** [comment]
yes I agree with you

**Comment by mangrish** [comment]
@tavolate Have you raised a ticket with https://github.com/neo4j/neo4j-java-driver/issues? Is it ok to close this issue? I'm not sure we can do much more here.

**Comment by nandosola** [comment]
@mangrish could you please have a look at https://github.com/neo4j/neo4j-ogm/issues/319 It seems that as long as `neo4j-ogm`throws the right exception, `spring-data-neo4j` could reconnect?
