### ISSUE TITLE
No default constructor found Exception org.springframework.data.neo4j.repository.support.Neo4jRepositoryFactoryBean

### ISSUE THREAD

**Issue by Alibay** [spring-projects/spring-data-neo4j#380]
After maven dependency has been updated

> <dependency>

	<groupId>org.springframework.data</groupId>
	<artifactId>spring-data-neo4j</artifactId>
	<version>4.2.0.BUILD-SNAPSHOT</version>
</dependency>

I got an error on app startup

> Failed to instantiate [org.springframework.data.neo4j.repository.support.Neo4jRepositoryFactoryBean]: No default constructor found; nested exception is java.lang.NoSuchMethodException: org.springframework.data.neo4j.repository.support.Neo4jRepositoryFactoryBean.<init>()

Using versions:
SDN: 4.2.0.BUILD-SNAPSHOT
OGM: 2.1.0-SNAPSHOT

Stacktrace:

> 2016-12-16 13:47:09.853 ERROR 6472 --- [           main] o.s.boot.SpringApplication               : Application startup failed org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'teamRepository': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.data.neo4j.repository.support.Neo4jRepositoryFactoryBean]: No default constructor found; nested exception is java.lang.NoSuchMethodException: org.springframework.data.neo4j.repository.support.Neo4jRepositoryFactoryBean.<init>()
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1110) ~[spring-beans-4.3.3.RELEASE.jar:4.3.3.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1055) ~[spring-beans-4.3.3.RELEASE.jar:4.3.3.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getSingletonFactoryBeanForTypeCheck(AbstractAutowireCapableBeanFactory.java:870) ~[spring-beans-4.3.3.RELEASE.jar:4.3.3.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryBean(AbstractAutowireCapableBeanFactory.java:797) ~[spring-beans-4.3.3.RELEASE.jar:4.3.3.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.isTypeMatch(AbstractBeanFactory.java:544) ~[spring-beans-4.3.3.RELEASE.jar:4.3.3.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:422) ~[spring-beans-4.3.3.RELEASE.jar:4.3.3.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:390) ~[spring-beans-4.3.3.RELEASE.jar:4.3.3.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:505) ~[spring-beans-4.3.3.RELEASE.jar:4.3.3.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:498) ~[spring-beans-4.3.3.RELEASE.jar:4.3.3.RELEASE]
        at org.springframework.security.config.annotation.web.configuration.OnMissingBeanCondition.matches(OnMissingBeanCondition.java:37) ~[spring-security-config-4.0.2.RELEASE.jar:4.0.2.RELEASE]
        at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:102) ~[spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForBeanMethod(ConfigurationClassBeanDefinitionReader.java:178) ~[spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:140) ~[spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:116) ~[spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:336) ~[spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:246) ~[spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:273) ~[spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:98) ~[spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:681) ~[spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:523) ~[spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.4.1.RELEASE.jar:1.4.1.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761) ~[spring-boot-1.4.1.RELEASE.jar:1.4.1.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:371) ~[spring-boot-1.4.1.RELEASE.jar:1.4.1.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-1.4.1.RELEASE.jar:1.4.1.RELEASE]
        at com.orkistra.Application.main(Application.java:75) [classes/:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.data.neo4j.repository.support.Neo4jRepositoryFactoryBean]: No default constructor found; nested exception is java.lang.NoSuchMethodException: org.springframework.data.neo4j.repository.support.Neo4jRepositoryFactoryBean.<init>()
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:85) ~[spring-beans-4.3.3.RELEASE.jar:4.3.3.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1103) ~[spring-beans-4.3.3.RELEASE.jar:4.3.3.RELEASE]
        ... 24 common frames omitted
Caused by: java.lang.NoSuchMethodException: org.springframework.data.neo4j.repository.support.Neo4jRepositoryFactoryBean.<init>()
        at java.lang.Class.getConstructor0(Class.java:3082) ~[na:1.8.0_66]
        at java.lang.Class.getDeclaredConstructor(Class.java:2178) ~[na:1.8.0_66]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:80) ~[spring-beans-4.3.3.RELEASE.jar:4.3.3.RELEASE]
        ... 25 common frames omitted

**Comment by geld0r** [comment]
Can confirm, I also see this error upon startup.
The last version that worked for me is "4.2.0.BUILD-20161208.141223-160" which is however no longer available in the snapshot-repository.

It looks like this was broken by:
https://github.com/spring-projects/spring-data-neo4j/commit/88a908321e1579a22291b13de9b1bc6895164e62

**Comment by mangrish** [comment]
@geld0r  @Alibay Can either of you provide an example? I cannot replicate this. I've tried it with our spring example project and there is no issue: https://github.com/neo4j-examples/sdn4-university/tree/spring-boot-1.5

Can you double check your config against that and see what you get?

**Comment by mangrish** [comment]
@Alibay: On second look at your stack trace it looks like your version of Spring-Data-Commons is out of date. Please refresh with the latest version and try again.

**Comment by Alibay** [comment]
@mangrish Yes, You are absolutely right. After update Spring-Data-Commons the problem has been solved. Thank You

**Comment by mangrish** [comment]
@Alibay No problems. @geld0r: Feel free to reopen if you still get issues.

**Comment by geld0r** [comment]
Can you specify which version or release train of spring-data-commons is required?

**Comment by Alibay** [comment]
@geld0r 1.13.0.BUILD-SNAPSHOT

**Comment by geld0r** [comment]
@Alibay: Thanks, that did the trick!
