### ISSUE TITLE
Error using PERIODIC keyword in cypher query with BoltDriver

### ISSUE THREAD

**Issue by mj9wj5ec** [spring-projects/spring-data-neo4j#381]
Is there a way to use the PERIODIC keyword in a cypher query with the ogm BoltDriver? I was able to work around it with the HttpDriver by making a request directly by calling Components.driver().request().execute( defaultRequest ) and not using Transactional annotations, but with the BoltDriver I see no corresponding workaround and I get an error:

```
org.neo4j.ogm.exception.CypherException: Error executing Cypher; Code: Neo.ClientError.Statement.SemanticError; Description: Executing queries that use periodic commit in an open transaction is not possible.
    at org.neo4j.ogm.drivers.bolt.transaction.BoltTransaction.commit(BoltTransaction.java:89)
    at org.neo4j.ogm.drivers.bolt.request.BoltRequest.executeRequest(BoltRequest.java:156)
    at org.neo4j.ogm.drivers.bolt.request.BoltRequest.execute(BoltRequest.java:89)
Caused by: org.neo4j.driver.v1.exceptions.ClientException: Executing queries that use periodic commit in an open transaction is not possible.
    at org.neo4j.driver.internal.connector.socket.SocketResponseHandler.handleFailureMessage(SocketResponseHandler.java:68)
    at org.neo4j.driver.internal.messaging.PackStreamMessageFormatV1$Reader.unpackFailureMessage(PackStreamMessageFormatV1.java:464)
    at org.neo4j.driver.internal.messaging.PackStreamMessageFormatV1$Reader.read(PackStreamMessageFormatV1.java:425)
    at org.neo4j.driver.internal.connector.socket.SocketClient.receiveOne(SocketClient.java:130)
    at org.neo4j.driver.internal.connector.socket.SocketClient.receiveAll(SocketClient.java:124)
    at org.neo4j.driver.internal.connector.socket.SocketConnection.receiveAll(SocketConnection.java:129)
    at org.neo4j.driver.internal.connector.socket.SocketConnection.sync(SocketConnection.java:108)
    at org.neo4j.driver.internal.connector.ConcurrencyGuardingConnection.sync(ConcurrencyGuardingConnection.java:136)
    at org.neo4j.driver.internal.pool.PooledConnection.sync(PooledConnection.java:157)
    at org.neo4j.driver.internal.InternalTransaction.close(InternalTransaction.java:110)
    at org.neo4j.ogm.drivers.bolt.transaction.BoltTransaction.commit(BoltTransaction.java:75)
    ... 47 more
```

Inside BoltRequest:153 it seems like the code is properly trying to use an autocommit, which PERIODIC should work in, but according to the error message it doesn't seem like neo4j thinks it's an auto commit, but an open transaction.

**Comment by mangrish** [comment]
From Slack (edited):

The OGM works with the HTTP driver is that if a transaction is explicitly opened then an underlying call to the database is opened until commit/rollback is called otherwise it uses the “autocommit” mode as you have found. On the surface to me this looks like a bug as the OGM may be using this same approach to process bolt queries which to me should result in the error you see.

**Comment by mj9wj5ec** [comment]
Opened https://github.com/neo4j/neo4j-ogm/issues/310
